<?php 
$wondertage_settings = array();
if (mysqli_query($wo['sqlConnect'], "DESCRIBE `wondertage_settings`" )) {
	$settings = $db->get('wondertage_settings');
	foreach ($settings as $key => $value) {
		$wondertage_settings[$value->name] = $value->value;
	}
}

$postVideo = unserialize(base64_decode($wo['story']['postVideo']));
$postVideoThumb = unserialize(base64_decode($wo['story']['postVideoThumb']));
$postVideosCount = count((array) $postVideo);

$postVideos = fixLastVideoLink($postVideo)
?>

<?php if (!empty($wondertage_settings) && $wondertage_settings['tag_artplayer'] == 1) { ?>
<!--	<div class="embed-responsive embed-responsive-16by9">-->
<!--		--><?php //if ($wo['story']['processing'] > 0 && (Wo_IsModerator() || Wo_IsAdmin() || $wo['story']['user_id'] == $wo['user']['id'])) { ?>
<!--			<div class="alert alert-warning vid_procss_alrt processing_alert_--><?php //echo $wo['media']['storyId'];?><!--"><span class="pointer" onclick="ProcessingVideo('--><?php //echo $wo['media']['storyId'];?>//')"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span><?php //echo $wo['lang']['processing_video']; ?><!--</div>-->
<!--		--><?php //} ?>
<!--		<div class="artplayer-app" id="video----><?php //echo $wo['media']['storyId'];?><!--"></div>-->
<!--	</div>-->

	<script>

	//var art = new Artplayer({
	//	container: '#video--<?php //echo $wo['media']['storyId'];?>//',
	//	url: '<?php //echo $wo['media']['filename'];?>//',
	//	poster: '<?php // echo $wo['media']['video_thumb'];?>//',
	//	volume: 1,
	//	pip: true,
	//	fullscreen: true,
	//	miniProgressBar: true,
	//	theme: '<?php //echo $wo['config']['btn_background_color'];?>//',
	//	icons: {
	//		state: '<svg class="playback-icons" xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path fill="currentColor" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 13.5v-7c0-.41.47-.65.8-.4l4.67 3.5c.27.2.27.6 0 .8l-4.67 3.5c-.33.25-.8.01-.8-.4z"/></svg>',
	//	},
	//	whitelist: ['*'],
	//	moreVideoAttr: {
	//		'webkit-playsinline': true,
	//		playsInline: true,
	//		preload: 'auto',
	//	},
	//	<?php //if (empty($wo['story']['240p_video']) && empty($wo['story']['360p_video'])  && empty($wo['story']['480p_video'])  && empty($wo['story']['720p_video'])  && empty($wo['story']['1080p_video'])  && empty($wo['story']['2048p_video'])  && empty($wo['story']['4096p_video'])) { ?>
	<!--	--><?php //}else{ ?>
	//		quality: [
	//			<?php //if (!empty($wo['story']['240p_video'])) { ?>
	//	    		{
	//					name: '240p',
	//					url: '<?php //echo($wo['story']['240p_video']) ?>//',
	//				},
	//	    	<?php //} ?>
	<!--			--><?php //if (!empty($wo['story']['360p_video'])) { ?>
	//	    		{
	//					name: '360p',
	//					url: '<?php //echo($wo['story']['360p_video']) ?>//',
	//				},
	//	    	<?php //} ?>
	<!--			--><?php //if (!empty($wo['story']['480p_video'])) { ?>
	//	    		{
	//					name: '480p',
	//					url: '<?php //echo($wo['story']['480p_video']) ?>//',
	//				},
	//	    	<?php //} ?>
	<!--			--><?php //if (!empty($wo['story']['720p_video'])) { ?>
	//	    		{
	//					name: '720p',
	//					url: '<?php //echo($wo['story']['720p_video']) ?>//',
	//				},
	//	    	<?php //} ?>
	<!--			--><?php //if (!empty($wo['story']['1080p_video'])) { ?>
	//	    		{
	//					name: '1080p',
	//					url: '<?php //echo($wo['story']['1080p_video']) ?>//',
	//				},
	//	    	<?php //} ?>
	<!--			--><?php //if (!empty($wo['story']['2048p_video'])) { ?>
	//	    		{
	//					name: '2048p',
	//					url: '<?php //echo($wo['story']['2048p_video']) ?>//',
	//				},
	//	    	<?php //} ?>
	<!--			--><?php //if (!empty($wo['story']['4096p_video'])) { ?>
	//	    		{
	//					name: '4096p',
	//					url: '<?php //echo($wo['story']['4096p_video']) ?>//',
	//				},
	//	    	<?php //} ?>
	//		],
	//	<?php //} ?>
	//});

	//art.on('ready', () => {
	//	$('#video--<?php //echo $wo['media']['storyId'];?>//').addClass('hide_control');
	//	$('.art-notice, .art-contextmenus').remove();
	//});
	//art.on('play', () => {
	//	Wo_AddVideoViews(<?php //echo $wo['media']['storyId'];?>//);
	//	$('#video--<?php //echo $wo['media']['storyId'];?>// .art-mask').remove();
	//	$('#video--<?php //echo $wo['media']['storyId'];?>//').removeClass('hide_control');
	//	art.events.proxy(window, 'scroll', function (e) {
	//		if (!document.pictureInPictureElement) {
	//			$('#video--<?php //echo $wo['media']['storyId'];?>// video').each(function(){
	//				if ($(this).is(":in-viewport")) {
    //
	//				} else {
	//					$(this)[0].pause();
	//				}
	//			});
	//		}
	//	});
	//});
	//art.on('pause', () => {
	//	$('#video--<?php //echo $wo['media']['storyId'];?>//').addClass('show_control');
	//});
	</script>
<?php } else { ?>
	    <div class="tag_vid_plyr tag_vid_plyr_2 d-flex">
		<?php if ($wo['story']['processing'] > 0 && (Wo_IsModerator() || Wo_IsAdmin() || $wo['story']['user_id'] == $wo['user']['id'])) { ?>
		<?php } ?>
            <?php if($postVideosCount) {for ($i = 0; $i < $postVideosCount; $i++) { ?>
				<div class='post_video_wrapper'>
            	    <div class='post_video_lightbox' onclick="Wo_OpenLightBox('<?php echo $wo['story']['id'] ?>', '', <?php echo $i; ?>)"></div>
					<video style="pointer-events: none" class="pr-1 plyr-video"  src="<?php echo $postVideos[$i]['filename']; ?>" id="video--<?php echo $postVideos[$i]['filename'] ?>"  playsinline preload="metadata" data-setup="{}" data-post-video="<?php echo $postVideos[$i]['filename']; ?>"></video>
				</div>
			<?php } }?>
        </div>
    <script>

    var tagvideo = $('.plyr-video');

    tagvideo.each((i,item) => {
        new Plyr(item, {
            controls: ['play-large', 'progress', 'play', 'mute', 'volume', 'current-time','duration', 'settings', 'pip', 'airplay', 'fullscreen'],
            <?php if (Wo_IsMobile() == false) { ?>
            ratio: '16:9',
            <?php } ?>
            fullscreen: {
                iosNative: true
            },
            ads: {
                enabled: false,
                tagUrl: ''
            }
        });
    })

	//var players = Plyr.setup(tagvideo, {
	//	controls: ['play-large', 'progress', 'play', 'mute', 'volume', 'current-time', 'settings', 'pip', 'airplay', 'fullscreen'],
	//	<?php //if (Wo_IsMobile() == false) { ?>
	//	ratio: '16:9',
	//	<?php //} ?>
	//	fullscreen: {
	//		iosNative: true
	//	},
	//	ads: {
	//		enabled: false,
	//		tagUrl: ''
	//	}
	//});

	$(window).scroll(function(e){
		if (!document.pictureInPictureElement) {
			$('.plyr-video').each(function(){
				if ($(this).is(":in-viewport")) {

				} else {
					$(this)[0].pause();
				}
			});
		}
	});
	</script>
<?php } ?>