<?php 
	$id                           = $user_id = $wo['setting']['user_id'];
	$wo['user_profile']           = Wo_UserData($user_id);
	$type                         = 'timeline';
	$about                        = $wo['user_profile']['about'];
	$name                         = $wo['user_profile']['name'];
	$wo['user_profile']['fields'] = Wo_UserFieldsData($user_id);
	$IsOwner       = Wo_IsOnwer($wo['user_profile']['user_id']);
	$IsOwnerUser   = Wo_IsOnwerUser($wo['user_profile']['user_id']);
			
?>
<style>
.wo_user_profile .user-avatar {
	margin: -70px auto 15px;
}
</style>
<h2 class="tag_page_title"><button type="button" class="btn setting_navigation" onclick="$('.tag_sett_sidebar').fadeIn(50);$('#tag_sett_right_prt').fadeOut(50);"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z" fill="currentColor"></path></svg></button> <?php echo $wo['lang']['avatar_and_cover']; ?></h2>
<div class="wow_sett_content wow_content p20">

<div class="page-margin profile wo_user_profile" data-page="timeline" data-id="<?php echo $wo['user_profile']['user_id'];?>">
	<div class="container-fluid tag_cont_fluid">
		<div class="profile-container tag_cover_bg">
			<?php if ($wo['config']['profile_back'] == 1) { ?>
				<?php if ($wo['user_profile']['background_image_status'] == '1') { ?>
				<?php } else { ?>
					<div class="tag_cover_sec_bg">
						<img src="<?php echo $wo['user_profile']['cover']?>">
						<div class="tag_cover_bg_grad"></div>
					</div>
				<?php } ?>
			<?php } else { ?>
				<div class="tag_cover_sec_bg">
					<img src="<?php echo $wo['user_profile']['cover']?>">
					<div class="tag_cover_bg_grad"></div>
				</div>
			<?php } ?>
			<div class="container">
				<div class="card hovercard">
					<div class="wow_content cardheader user-cover">
						<?php if($IsOwnerUser === false) { ?>
						<?php if($wo['loggedin'] == true) { ?>
						<div class="dropdown tag_user_prof_opts">
							<div class="dropdown-toggle pointer" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
								<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path fill="currentColor" d="M12 8c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm0 2c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0 6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z"/></svg>
							</div>
							<ul class="dropdown-menu dropdown-menu-right tag_create_menu" role="menu">
								<?php if($wo['loggedin'] == true && $IsOwner) { ?>
									<li>
										<a href="<?php echo Wo_SeoLink('index.php?link1=setting&user=' . $wo['user_profile']['username'] . '&page=general-setting') ?>">
											<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" class="hover_path" d="M9.243 19H21v2H3v-4.243l9.9-9.9 4.242 4.244L9.242 19zm5.07-13.556l2.122-2.122a1 1 0 0 1 1.414 0l2.829 2.829a1 1 0 0 1 0 1.414l-2.122 2.121-4.242-4.242z"></path><path fill="currentColor" d="M5 19h1.414l9.314-9.314-1.414-1.414L5 17.586V19zm16 2H3v-4.243L16.435 3.322a1 1 0 0 1 1.414 0l2.829 2.829a1 1 0 0 1 0 1.414L9.243 19H21v2zM15.728 6.858l1.414 1.414 1.414-1.414-1.414-1.414-1.414 1.414z"></path></svg> <?php echo $wo['lang']['edit_user'];?>
										</a>
									</li>
								<?php } ?>
                                <?php if($IsOwnerUser === false && $wo['loggedin'] == true && $wo['config']['poke_system'] == 1) { ?>
									<li id="pokebutton">
										<a class="pointer" onclick="Wo_RegisterPoke(<?php echo $wo['user_profile']['user_id'];?>,<?php echo $wo['user']['user_id'];?>)">
											<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" class="hover_path" d="M12 2c5.52 0 10 4.48 10 10s-4.48 10-10 10S2 17.52 2 12 6.48 2 12 2zm0 8c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z"></path><path fill="currentColor" d="M12 20a8 8 0 1 0 0-16 8 8 0 0 0 0 16zm0 2C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zm0-8a2 2 0 1 1 0-4 2 2 0 0 1 0 4z"></path></svg> <?php echo $wo['lang']['poke_user'];?>
										</a>
									</li>
								<?php } ?>
								<?php if($IsOwnerUser === false && $wo['loggedin'] == true && !Wo_IsFamilyMemberExists($wo['user']['id'],$wo['user_profile']['id'],false) && $wo['config']['website_mode'] != 'instagram') { ?>
									<li id="open_add_to_family_modal">
										<a class="pointer" onclick="$('#add_to_family').modal('show');">
											<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" class="hover_path" d="M14 14.252V22H4a8 8 0 0 1 10-7.748zM12 13c-3.315 0-6-2.685-6-6s2.685-6 6-6 6 2.685 6 6-2.685 6-6 6zm6 4v-3h2v3h3v2h-3v3h-2v-3h-3v-2h3z"></path><path fill="currentColor" d="M14 14.252v2.09A6 6 0 0 0 6 22l-2-.001a8 8 0 0 1 10-7.748zM12 13c-3.315 0-6-2.685-6-6s2.685-6 6-6 6 2.685 6 6-2.685 6-6 6zm0-2c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm6 6v-3h2v3h3v2h-3v3h-2v-3h-3v-2h3z"></path></svg> <?php echo $wo['lang']['add_to_family'];?>
										</a>
									</li>
								<?php } ?>
								<?php if($IsOwnerUser === false && $wo['loggedin'] == true) { ?>
									<hr>
									<li>
										<a href="<?php echo $wo['marker'] . 'block_user=block'?>">
											<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" class="hover_path" d="M15.936 2.5L21.5 8.067v7.87L15.936 21.5h-7.87L2.5 15.936v-7.87L8.066 2.5h7.87zM8 11v2h8v-2H8z"></path><path fill="currentColor" d="M15.936 2.5L21.5 8.067v7.87L15.936 21.5h-7.87L2.5 15.936v-7.87L8.066 2.5h7.87zm-.829 2H8.894L4.501 8.895v6.213l4.393 4.394h6.213l4.394-4.394V8.894l-4.394-4.393zM8 11h8v2H8v-2z"></path></svg> <?php echo $wo['lang']['block_user'];?>
										</a>
									</li>
								<?php } ?>
								
								<?php if($IsOwnerUser === false && $wo['loggedin'] == true && !$wo['user_profile']['is_reported_user']) { ?>
									<li>
										<a class="pointer" href="javascript:void(0)" onclick="Wo_OpenReportBox()">
											<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" class="hover_path" d="M16.218 2.5l5.683 5.682v8.036l-5.683 5.683H8.182l-5.683-5.683V8.182l5.683-5.683h8.036zM11 15v2h2v-2h-2zm0-8v6h2V7h-2z"></path><path fill="currentColor" d="M15.936 2.5L21.5 8.067v7.87L15.936 21.5h-7.87L2.5 15.936v-7.87L8.066 2.5h7.87zm-.829 2H8.894L4.501 8.895v6.213l4.393 4.394h6.213l4.394-4.394V8.894l-4.394-4.393zM11 15h2v2h-2v-2zm0-8h2v6h-2V7z"></path></svg> <?php echo $wo['lang']['report_user_text'];?>
										</a>
									</li>
								<?php }elseif ($IsOwnerUser === false && $wo['loggedin'] == true && $wo['user_profile']['is_reported_user']) { ?>
									<li>
										<a class="pointer" href="javascript:void(0)" onclick="Wo_UnreportReportUser()">
											<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" class="hover_path" d="M16.218 2.5l5.683 5.682v8.036l-5.683 5.683H8.182l-5.683-5.683V8.182l5.683-5.683h8.036zM11 15v2h2v-2h-2zm0-8v6h2V7h-2z"></path><path fill="currentColor" d="M15.936 2.5L21.5 8.067v7.87L15.936 21.5h-7.87L2.5 15.936v-7.87L8.066 2.5h7.87zm-.829 2H8.894L4.501 8.895v6.213l4.393 4.394h6.213l4.394-4.394V8.894l-4.394-4.393zM11 15h2v2h-2v-2zm0-8h2v6h-2V7z"></path></svg> <?php echo $wo['lang']['unreport'];?>
										</a>
									</li>
								<?php } ?>
							</ul>
						</div>
						<?php } ?>
						<?php } ?>
						<?php if($IsOwner === true) { ?>
							<form action="#" method="post" class="profile-cover-changer">
								<div class="when-notedit profile_cover">
									<span class="btn btn-file btn-mat cover_modal_trigger">
										<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path fill="currentColor" d="M23 18V6c0-1.1-.9-2-2-2H3c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h18c1.1 0 2-.9 2-2zM8.9 12.98l2.1 2.53 3.1-3.99c.2-.26.6-.26.8.01l3.51 4.68c.25.33.01.8-.4.8H6.02c-.42 0-.65-.48-.39-.81L8.12 13c.19-.26.57-.27.78-.02z"></path></svg> <?php echo $wo['lang']['cover']?>
									</span>
									<input id="cover_input" class="hidden" onchange="Wo_UpdateProfileCover();" type="file" name="cover" accept="image/x-png, image/jpeg">
									<span class="btn btn-file btn-mat btn-sm tag_prof_repos_hide" onclick="Wo_StartRepositioner();" title="<?php echo $wo['lang']['drag_to_re']?>">
										<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path fill="currentColor" d="M13,6V11H18V7.75L22.25,12L18,16.25V13H13V18H16.25L12,22.25L7.75,18H11V13H6V16.25L1.75,12L6,7.75V11H11V6H7.75L12,1.75L16.25,6H13Z"></path></svg>
									</span>
								</div>
								<div class="when-edit" style="display: none;">
									<span class="btn btn-file btn-mat btn-sm" onclick="Wo_SubmitRepositioner();">
										<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path fill="currentColor" d="M9 16.17L5.53 12.7c-.39-.39-1.02-.39-1.41 0-.39.39-.39 1.02 0 1.41l4.18 4.18c.39.39 1.02.39 1.41 0L20.29 7.71c.39-.39.39-1.02 0-1.41-.39-.39-1.02-.39-1.41 0L9 16.17z"></path></svg>
									</span>
									<span class="btn btn-file btn-mat btn-sm" onclick="Wo_StopRepositioner();">
										<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path fill="currentColor" d="M18.3 5.71c-.39-.39-1.02-.39-1.41 0L12 10.59 7.11 5.7c-.39-.39-1.02-.39-1.41 0-.39.39-.39 1.02 0 1.41L10.59 12 5.7 16.89c-.39.39-.39 1.02 0 1.41.39.39 1.02.39 1.41 0L12 13.41l4.89 4.89c.39.39 1.02.39 1.41 0 .39-.39.39-1.02 0-1.41L13.41 12l4.89-4.89c.38-.38.38-1.02 0-1.4z"></path></svg>
									</span>
								</div>
								<input type="hidden" name="user_id" value="<?php echo $wo['user_profile']['user_id'];?>">
							</form>
							<form class="cover-position-form hidden" method="post">
								<input class="cover-position" name="pos" value="0" type="hidden">
								<input class="image_type" name="image_type" value="0" type="hidden">
								<input name="cover_image" id="cover-input-image" value="<?php echo $wo['user_profile']['cover_org']?>" type="hidden">
								<input name="real_image" id="full-input-image" value="<?php echo Wo_GetMedia($wo['user_profile']['cover_full']); ?>" type="hidden">
								<input type="hidden" name="type" value="user_cover">
								<input type="hidden" name="user_id" value="<?php echo $wo['user_profile']['user_id'];?>">
							</form>
						<?php } ?>
						<div class="user-cover-uploading-progress">
							<div class="pace-activity-parent"><div class="pace-activity"></div></div>
						</div>
						<div class="tag_usr_prof_covr">
							<div class="user-cover-reposition-container">
								<div class="user-cover-reposition-w">
									<img id="cover-image" src="<?php echo $wo['user_profile']['cover']?>" alt="<?php echo $wo['user_profile']['name']?>" onclick="Wo_OpenProfileCover('<?php echo $wo['user_profile']['cover_org']?>');" class="pointer"/>
								</div>
								<div class="user-reposition-container">
									<img id="full-image" src="<?php echo Wo_GetMedia($wo['user_profile']['cover_full'])?>" alt="User Image"/>
									<div class="user-reposition-dragable-container">
										<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path fill="currentColor" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 15c-.55 0-1-.45-1-1v-4c0-.55.45-1 1-1s1 .45 1 1v4c0 .55-.45 1-1 1zm1-8h-2V7h2v2z"/></svg> <?php echo $wo['lang']['drag_to_re']; ?>
									</div>
									<div class="user-cover-uploading-progress user-repositioning-icons-container"></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="wow_content p15 tag_page_name_hdr">
				<div class="event-info-cont-small">
					<div class="user-avatar flip <?php if ($wo['have_stories'] == true && $wo['story_seen_class'] != 'seen_story' && $wo['loggedin'] == true) { ?><?php echo($wo['story_seen_class']); ?><?php } ?>">
						<div class="user-avatar-uploading-container">
							<div class="pace-activity-parent"><div class="pace-activity"></div></div>
						</div>
						<img id="updateImage-<?php echo $wo['user_profile']['user_id']?>" class="pointer <?php if ($wo['have_stories'] == true && $wo['story_seen_class'] != 'seen_story' && $wo['loggedin'] == true) { ?><?php echo($wo['story_seen_class']); ?> see_all_stories<?php } ?>" alt="<?php echo $wo['user_profile']['name']?>" src="<?php echo $wo['user_profile']['avatar']?>" <?php if ($wo['have_stories'] == true && $wo['story_seen_class'] != 'seen_story' && $wo['loggedin'] == true) { ?> data_story_user_id="<?php echo $wo['user_profile']['user_id']?>"  data_story_type="user" <?php } else{ ?> onclick="Wo_OpenProfilePicture('<?php echo $wo['user_profile']['avatar_org']?>');" <?php } ?> />
						<?php if($IsOwner === true) { ?>
							<form action="#" method="post" class="profile-avatar-changer profile_avatar">
								<div class="dropdown">
									<span class="btn btn-file btn-mat" data-toggle="dropdown" role="button" aria-expanded="false"><svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24" fill="currentColor"><path d="M0 0h24v24H0V0z" fill="none"/><circle cx="12" cy="12" r="3"/><path d="M20 4h-3.17l-1.24-1.35c-.37-.41-.91-.65-1.47-.65H9.88c-.56 0-1.1.24-1.48.65L7.17 4H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm-8 13c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5z"/></svg></span>
									<ul class="dropdown-menu tag_create_menu" role="menu">
										<li>
											<a class="btn-file pointer">
												<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" class="hover_path" d="M2 6c0-.552.455-1 .992-1h18.016c.548 0 .992.445.992 1v14c0 .552-.455 1-.992 1H2.992A.994.994 0 0 1 2 20V6zm12 12a5 5 0 1 0 0-10 5 5 0 0 0 0 10zM4 7v2h3V7H4zm0-5h6v2H4V2z"></path><path fill="currentColor" d="M2 6c0-.552.455-1 .992-1h18.016c.548 0 .992.445.992 1v14c0 .552-.455 1-.992 1H2.992A.994.994 0 0 1 2 20V6zm2 1v12h16V7H4zm10 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm0 2a5 5 0 1 1 0-10 5 5 0 0 1 0 10zM4 2h6v2H4V2z"></path></svg> <?php echo $wo['lang']['upload_your_photo']; ?>
												<input type="file" name="avatar" accept="image/x-png, image/jpeg" onchange="Wo_UpdateProfileAvatar();">
											</a>
										</li>
										<?php if ($wo['user_profile']['avatar_org'] != $wo['userDefaultAvatar'] && $wo['user_profile']['avatar_org'] != $wo['userDefaultFAvatar']) {?>
											<li>
												<a class="pointer" onclick="OpenCropModal()">
													<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" class="hover_path" d="M19 17h3v2h-3v3h-2v-3H6a1 1 0 0 1-1-1V7H2V5h3V2h2v3h11a1 1 0 0 1 1 1v11z"></path><path fill="currentColor" d="M15 17v2H6a1 1 0 0 1-1-1V7H2V5h3V2h2v15h8zm2 5V7H9V5h9a1 1 0 0 1 1 1v11h3v2h-3v3h-2z"></path></svg> <?php echo $wo['lang']['crop_your_avatar']; ?>
												</a>
											</li>
										<?php } ?>
									</ul>
								</div>
								<input type="hidden" name="user_id" id="user-id" value="<?php echo $wo['user_profile']['user_id'];?>">
							</form>
						<?php } ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


	<div class="modal fade" id="cropImage" role="dialog">
		<div class="modal-dialog wow_mat_mdl modal-md">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title"><?php echo $wo['lang']['crop_your_avatar'] ?></h4>
				</div>
				<div class="modal-body">
					<div id="image-to-crop" class="wo_crop_img_pic">
						<img src="<?php echo Wo_GetMedia($wo['user_profile']['avatar_full'])?>" alt="avatar" data-image="<?php echo $wo['user_profile']['avatar_full']; ?>" >
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default btn-mat disable_btn" data-dismiss="modal" aria-label="Close"><?php echo $wo['lang']['cancel'] ?></button>
					<button type="button" class="btn btn-main btn-mat disable_btn" onclick="CropImage();"><?php echo $wo['lang']['save']; ?></button>
				</div>
			</div>
		</div>
	</div>

	
<div class="modal fade" id="cover_prompt_modal" role="dialog" data-keyboard="false">
    <div class="modal-dialog modal-md wow_mat_mdl">
        <div class="modal-content">
            <div class="modal-header">
                <p style="font-weight: bold">
                    <?php echo $wo["lang"]["add_cover"]?>
                </p>
            </div>
            <div class="modal-body">
                <div class="cover_modal_img">
                    <img src="<?php echo $wo['config']['theme_url'];?>/img/select-message.png" alt="">
                </div>
                <div class="cover_prompt_label">
                    <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                        <path fill="rgb(42, 88, 133)" d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
                    </svg>
                    <p class="cover_prompt_blue"><?php echo $wo['lang']['upload_cover']?></p>
                    <p class='cover_prompt'><?php echo $wo['lang']['cover_prompt']?></p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-mat close_cover_modal"><?php echo $wo['lang']['close'] ?></button>
            </div>
        </div>
    </div>
</div>

<?php echo Wo_LoadPage('modals/profile-picture');?>
<?php echo Wo_LoadPage('modals/cover-image');?>
<?php if (!empty($wo['user_profile']['background_image']) && $wo['user_profile']['background_image_status'] == 1) { ?>
<style>
body {background: url(<?php echo Wo_GetMedia($wo['user_profile']['background_image']); ?>) fixed !important;background-size:100% auto;}
</style>
<?php } ?>
<script>
jQuery(document).ready(function() {jQuery('.custom-fixed-side').theiaStickySidebar({additionalMarginTop: -15});});

$(".cover_modal_trigger").on('click', function(e) {
	e.preventDefault()
	console.log($('#cover_prompt_modal'))
	$('#cover_prompt_modal').toggleClass("show")
}) 

$(".close_cover_modal").on('click', function(e) {
	$('#cover_prompt_modal').removeClass("show")
}) 

$('.cover_prompt_label').on('click', function(e) {
	$('#cover_input').trigger("click")
}) 

$(function(){
    var url = window.location.pathname, 
        urlRegExp = new RegExp(url.replace(/\/$/,'') + "$"); // create regexp to match current url pathname and remove trailing slash if present as it could collide with the link in navigation in case trailing slash wasn't present there
        // now grab every link from the navigation
        $('.user-bottom-nav a').each(function(){
            // and test its normalized href against the url pathname regexp
            if(urlRegExp.test(this.href.replace(/\/$/,''))){
                $(this).addClass('menuactive');
            }
        });
	<?php if ($wo['nodejs_send_notification'] == true) { ?>
    	if (node_socket_flow == "1") {
    		socket.emit("user_notification", { to_id: $('.wo_user_profile').attr('data-id'), user_id: _getCookie("user_id")});
    	}
    <?php } ?>
});


function OpenCropModal() {
	$('#cropImage').modal('show');
	setTimeout(function () {
    	$('#image-to-crop img').rcrop({
            minSize : [130,130],
            preserveAspectRatio : true,
            grid : true,
        });
    }, 250);
}
function CropImage() {
    values = $('#image-to-crop img').rcrop('getValues');
    $path = $('#image-to-crop img').attr('data-image');
    if (!$path) {
    	return false;
    	$('#cropImage').modal('hide');
    }
    $('#cropImage').find('.disable_btn').attr('disabled','disabled');
    $.post(Wo_Ajax_Requests_File() + '?f=crop-avatar', {user_id:<?php echo $wo['user_profile']['id']; ?>, path: $path, x: values.x, y:values.y, height: values.height, width:values.width}, function(data, textStatus, xhr) {
        if (data.status == 200) {
        	location.reload(false);
        } else {
        	$('#cropImage').modal('hide');
        }
        $('#cropImage').find('.disable_btn').removeAttr("disabled");
    });
}

var user_id = $('.profile').attr('data-id');
$(function () {
  user_id = $('.profile').attr('data-id');
  <?php 
  if (!empty($_GET['story'])) {
    ?>
    Wo_LoadStory('prof', $('[data-page=timeline]').attr('data-id'));
    <?php
  }
  ?>
  
  $('form.profile-avatar-changer').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=update_user_avatar_picture',

    beforeSend: function () {
      $('.profile_avatar').fadeOut(100);
      $('.user-avatar-uploading-container').fadeIn(200);
    },
    success: function (data) {
      $('.profile_avatar').fadeIn(100);
      if(data.status == 200) {
        Wo_GetNewPosts();
        $('[id^=updateImage-<?php echo $wo['user_profile']['id']; ?>]').attr('data-target', '#ProfileImageModal-Stopped'); 
        $('[id^=updateImage-<?php echo $wo['user_profile']['id']; ?>]').attr('onclick', 'Wo_OpenProfilePicture("' + data.img_or + '");');
        $('[id^=updateImage-<?php echo $wo['user_profile']['id']; ?>]').attr("src", data.img);
        $('#cropImage').modal('show');
		<?php if ($wo['config']['node_socket_flow'] == "1") { ?>
            socket.emit("on_avatar_changed", {from_id: _getCookie("user_id"), name: data.img});
        <?php } ?>
        $('#image-to-crop img').attr('src', data.avatar_full);
        $('#image-to-crop img').attr('data-image', data.avatar_full_or);
        $('#image-to-crop img').on("load", function() {
		    setTimeout(function () {
		    	$('#image-to-crop img').rcrop({
		            minSize : [130,130],
		            preserveAspectRatio : true,
		            grid : true
		        });
		    }, 1000);
		}).each(function() {
		  if(this.complete) $(this).load();
		});
        if($("ul[data-profile-completion]").length == 1) {
            if ($('#add-profile-avatar').length == 1) {
               // window.location.reload();
            }
        }
      } else {
			if(data.invalid_file == 3){
				$("body").snackbar({
					message: "<?php echo $wo['lang']['adult_image_file']; ?>"
				});
			}
		}
      $('.user-avatar-uploading-container').fadeOut(200);
    }
  });

  $('form.cover-position-form').ajaxForm({
        url:  Wo_Ajax_Requests_File() + '?f=re_cover',
        dataType:  'json', 
        beforeSend: function() {
            $('.user-reposition-dragable-container').hide();
            $('.user-repositioning-icons-container').html('<div class="pace-activity-parent"><div class="pace-activity"></div></div>').fadeIn('fast');
        },
        success: function(data) {
            if (data.status == 200) {
				console.log(data)
                $('.user-cover-reposition-w img').attr('src', data.url + '?time=' + Math.random()).on("load", function () {
                    $('.when-edit').hide();
                    $('.when-notedit').show();
                    $('.user-repositioning-icons-container').fadeOut('fast').html('');
                    $('.user-cover-reposition-w').show();
                    $('.user-reposition-container').hide().find('img').css('top', 0);
                    $('.cover-resize-buttons').hide();
                    $('.default-buttons').show();
                    $('input.cover-position').val(0);
					$('.wo_user_profile .card.hovercard .pic-info-cont, .problackback').fadeIn();
                });
            }
        }
    });
  $('.profile-cover-changer').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=update_user_cover_picture',

    beforeSend: function () {
      $('.profile_cover').fadeOut(100);
      $('.user-cover-uploading-container,.user-cover-uploading-progress').fadeIn(200);
    },
    success: function (data) {
      $('.profile_cover').fadeIn(100);
      if(data.status == 200) {
        Wo_GetNewPosts();
        $('[id^=cover-image]').attr('data-target', '#ProfileCoverImageModal-Stopped');      
        $('[id^=cover-image]').attr('onclick', 'Wo_OpenProfileCover("' + data.cover_or + '");');
        $('[id^=cover-image]').attr("src", data.img);
        $('#full-image').attr("src", data.cover_full);
        $('#full-input-image').val(data.cover_full);
        $('#cover-input-image').val(data.cover_or);
        Wo_StartRepositioner();
      } else {
			if(data.invalid_file == 3){
				$("body").snackbar({
					message: "<?php echo $wo['lang']['adult_image_file']; ?>"
				});
			}
		}
      $('.user-cover-uploading-container,.user-cover-uploading-progress').fadeOut(200);
    }
  });
});

function Wo_UpdateProfileAvatar() {
  $("form.profile-avatar-changer").submit();
}

function Wo_UpdateProfileCover() {
  $("#cover_prompt_modal").removeClass('show')
  $("form.profile-cover-changer").submit();
}

function Wo_SetCookieAlert() {
  $.get(Wo_Ajax_Requests_File(), {
    f: 'set_admin_alert_cookie'
  });
}

function Wo_OpenProfileCover(image) {
    $.post(Wo_Ajax_Requests_File() + '?f=get_user_profile_cover_image_post', {
      image:image
    }, function (data) {
        if (data.status == 200) {
            Wo_OpenLightBox(data.post_id);
        } else {
            $('[id^=cover-image]').attr('data-target', '#ProfileCoverImageModal');
            $('[id^=cover-image]').attr('data-toggle', 'modal');
            $('#ProfileCoverImageModal').modal('show');
        }
    });
}

function Wo_OpenProfilePicture(image) {
    $.post(Wo_Ajax_Requests_File() + '?f=get_user_profile_image_post', {
      image:image
    }, function (data) {
        if (data.status == 200) {
            Wo_OpenLightBox(data.post_id);
        } else {
            $('[id^=updateImage-' + user_id + ']').attr('data-target', '#ProfileImageModal-' + user_id);
            $('[id^=updateImage-' + user_id + ']').attr('data-toggle', 'modal');
            $('#ProfileImageModal-' + user_id).modal('show');
        }
    });
}


</script>


</div>