<label class="tag_field">
	<?php $fid = '';
		  $searchForValue = ',';	
		if (!empty($wo['setting']['fileds'][$wo['field']['fid']])) {
			$fid = $wo['setting']['fileds'][$wo['field']['fid']];
			if ( strpos($fid, $searchForValue) !== false ) {
				 $fid = @explode(',', $fid);
				 $multiple_select = true;
			}
		} 
		if( isset( $_GET[ $wo['field']['fid'] ] ) && !empty( $_GET[ $wo['field']['fid'] ] ) ){
			$fid = Wo_Secure( $_GET[ $wo['field']['fid'] ] );
			if ( strpos($fid, $searchForValue) !== false ) {
				 $fid = @explode(',', $fid);
				 $multiple_select = true;
			}
		}
	?>
	<?php 
		if ($wo['field']['select_type'] == 'yes') {
		$options = @explode(',', $wo['field']['type']); ?>
		<style>
			.tag_field > input, .tag_field > select, .tag_field > .dropdown.bootstrap-select {
				height: 100px;
			}
		</style>
		<select name="<?php echo $wo['field']['fid'];?>" multiple>
				<?php if( isset( $wo['field']['issearch'] ) ){ ?> <option value=""><?php echo $wo['lang']['all'];?></option> <?php } ?>
				<?php
					foreach ($options as $key => $value) {
					if (is_array($fid)){
						if (in_array(($key + 1), $fid)){
						  $selected = 'selected';
						}else {
						  $selected = '';
						}
					} else{
						$selected = (($key + 1) == $fid) ? 'selected' : '';
					}
				?>
				<option value="<?php echo $key + 1;?>" <?php echo $selected;?>><?php echo $value;?></option>
				<?php } ?>
		</select>
	<?php } else { if ($wo['field']['type'] == 'textbox') { ?>
		<input id="<?php echo $wo['field']['fid'];?>" name="<?php echo $wo['field']['fid'];?>" type="text" placeholder=" " value="<?php echo $fid?>">
	<?php } else if ($wo['field']['type'] == 'textarea') {?>
		<textarea placeholder=" " id="<?php echo $wo['field']['fid'];?>" name="<?php echo $wo['field']['fid'];?>" rows="3"><?php echo br2nl($fid);?></textarea>
	<?php } } ?>
	<span><?php echo $wo['field']['name'];?> </span>
</label>
<?php if( !isset( $wo['field']['issearch'] ) ){ ?>
	<div class="help-block"><?php echo $wo['field']['description']; ?> <?php if($wo['field']['id'] == 3) {echo $wo['lang']['in_woodworking'];} ?></div>
<?php } ?>