<div class="wow_sett_content not-profile-content">
    <form action="#" method="post" class="profile-cover-changer not-profile">
        <div class="user-cover-reposition-container">
            <div class="user-cover-reposition-w">
                <img class="w-100" id="cover-image" src="<?php echo $wo['setting']['cover']?>" alt="<?php echo $wo['setting']['name']?>" class="pointer"/>
            </div>
            <div class="user-reposition-container">
                <img id="full-image" src="<?php echo Wo_GetMedia($wo['setting']['cover_full'])?>" alt="User Image"/>
                <div class="user-reposition-dragable-container">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path fill="currentColor" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 15c-.55 0-1-.45-1-1v-4c0-.55.45-1 1-1s1 .45 1 1v4c0 .55-.45 1-1 1zm1-8h-2V7h2v2z"/></svg> <?php echo $wo['lang']['drag_to_re']; ?>
                </div>
                <div class="user-cover-uploading-progress user-repositioning-icons-container"></div>
            </div>
        </div>
        <input type="hidden" name="page_id" id="page-id" value="<?php echo $wo['setting']['id'];?>">
        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
        <div class="when-notedit profile_cover">
            <span class="btn btn-file btn-mat cover_modal_trigger" title="<?php echo $wo['lang']['choose_cover']?>">
                <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path fill="currentColor" d="M23 18V6c0-1.1-.9-2-2-2H3c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h18c1.1 0 2-.9 2-2zM8.9 12.98l2.1 2.53 3.1-3.99c.2-.26.6-.26.8.01l3.51 4.68c.25.33.01.8-.4.8H6.02c-.42 0-.65-.48-.39-.81L8.12 13c.19-.26.57-.27.78-.02z"></path></svg> <?php echo $wo['lang']['cover']?>
            </span>
            <input class='hidden' id="cover_input" type="file" name="cover" accept="image/x-png, image/jpeg" onchange="Wo_UpdateProfileCover();">
            <span class="btn btn-file btn-mat btn-sm tag_prof_repos_hide" onclick="Wo_StartRepositioner();" title="<?php echo $wo['lang']['drag_to_re']?>">
                <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path fill="currentColor" d="M13,6V11H18V7.75L22.25,12L18,16.25V13H13V18H16.25L12,22.25L7.75,18H11V13H6V16.25L1.75,12L6,7.75V11H11V6H7.75L12,1.75L16.25,6H13Z"></path></svg>
            </span>
        </div>
        <div class="when-edit" style="display: none;">
            <span class="btn btn-file btn-mat btn-sm" onclick="Wo_SubmitRepositioner();">
                <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path fill="currentColor" d="M9 16.17L5.53 12.7c-.39-.39-1.02-.39-1.41 0-.39.39-.39 1.02 0 1.41l4.18 4.18c.39.39 1.02.39 1.41 0L20.29 7.71c.39-.39.39-1.02 0-1.41-.39-.39-1.02-.39-1.41 0L9 16.17z"></path></svg>
            </span>
            <span class="btn btn-file btn-mat btn-sm" onclick="Wo_StopRepositioner();">
                <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path fill="currentColor" d="M18.3 5.71c-.39-.39-1.02-.39-1.41 0L12 10.59 7.11 5.7c-.39-.39-1.02-.39-1.41 0-.39.39-.39 1.02 0 1.41L10.59 12 5.7 16.89c-.39.39-.39 1.02 0 1.41.39.39 1.02.39 1.41 0L12 13.41l4.89 4.89c.39.39 1.02.39 1.41 0 .39-.39.39-1.02 0-1.41L13.41 12l4.89-4.89c.38-.38.38-1.02 0-1.4z"></path></svg>
            </span>
        </div>
    </form>
    <form class="cover-position-form hidden" method="post">
        <input class="cover-position" name="pos" value="0" type="hidden">
        <input class="image_type" name="image_type" value="0" type="hidden">
        <input name="cover_image" id="cover-input-image" value="<?php echo $wo['setting']['cover_org']?>" type="hidden">
        <input name="real_image" id="full-input-image" value="<?php echo Wo_GetMedia($wo['setting']['cover_full']); ?>" type="hidden">
        <input type="hidden" name="user_id" value="<?php echo $wo['setting']['page_id'];?>">
        <input type="hidden" name="type" value="page_cover">
    </form>
	<form method="post" class="form-horizontal setting-profile-form" enctype="multipart/form-data">
		<div class="setting-profile-alert setting-update-alert"></div>
<!--		<div class="wow_cset_cover" title="--><?php //echo $wo['lang']['cover']; ?><!--">-->
<!--            <div class="wow_cset_cover_hdr">-->
<!--                <span class="btn btn-file valign" id="coverimage-holder" onclick="$('#cover').trigger('click'); return false;">-->
<!--                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M14,6L10.25,11L13.1,14.8L11.5,16C9.81,13.75 7,10 7,10L1,18H23L14,6Z" /></svg>-->
<!--                </span>-->
<!--                <input type="file" class="hidden" id="cover" accept="image/x-png, image/gif, image/jpeg" name="cover">-->
<!--            </div>-->
<!--			<div class="avatar-read" id="cover-form"><p></p></div>-->
<!--		</div>-->
        
        <div class="wow_cset_avtr">
            <div class="wow_cset_avtr_hdr">

                <span class="btn btn-file valign" id="avatarimage-holder" title="<?php echo $wo['lang']['avatar']; ?>">

                    <div class="profile-avatar-changer dropdown">
                        <span class="btn btn-file btn-mat" data-toggle="dropdown" role="button" aria-expanded="false"><svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24" fill="currentColor"><path d="M0 0h24v24H0V0z" fill="none"/><circle cx="12" cy="12" r="3"/><path d="M20 4h-3.17l-1.24-1.35c-.37-.41-.91-.65-1.47-.65H9.88c-.56 0-1.1.24-1.48.65L7.17 4H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm-8 13c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5z"/></svg></span>
                        <ul class="dropdown-menu tag_create_menu" role="menu">
                            <li onclick="$('#avatar').trigger('click'); return false;">
                                <a class="btn-file pointer">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" class="hover_path" d="M2 6c0-.552.455-1 .992-1h18.016c.548 0 .992.445.992 1v14c0 .552-.455 1-.992 1H2.992A.994.994 0 0 1 2 20V6zm12 12a5 5 0 1 0 0-10 5 5 0 0 0 0 10zM4 7v2h3V7H4zm0-5h6v2H4V2z"></path><path fill="currentColor" d="M2 6c0-.552.455-1 .992-1h18.016c.548 0 .992.445.992 1v14c0 .552-.455 1-.992 1H2.992A.994.994 0 0 1 2 20V6zm2 1v12h16V7H4zm10 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm0 2a5 5 0 1 1 0-10 5 5 0 0 1 0 10zM4 2h6v2H4V2z"></path></svg> <?php echo $wo['lang']['upload_your_photo']; ?>
                                </a>
                            </li>
                            <?php if ($wo['config']['ai_user_system'] == 1) { ?>
                                <li>
                                    <a class="btn-file pointer" onclick="openAiUserModel()">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" class="hover_path" d="M14 20H10V22H8V20H5C4.44772 20 4 19.5523 4 19V16H2V14H4V10H2V8H4V5C4 4.44772 4.44772 4 5 4H8V2H10V4H14V2H16V4H19C19.5523 4 20 4.44772 20 5V8H22V10H20V14H22V16H20V19C20 19.5523 19.5523 20 19 20H16V22H14V20ZM7 7V11H11V7H7Z"></path><path fill="currentColor" d="M6 18H18V6H6V18ZM14 20H10V22H8V20H5C4.44772 20 4 19.5523 4 19V16H2V14H4V10H2V8H4V5C4 4.44772 4.44772 4 5 4H8V2H10V4H14V2H16V4H19C19.5523 4 20 4.44772 20 5V8H22V10H20V14H22V16H20V19C20 19.5523 19.5523 20 19 20H16V22H14V20ZM8 8H16V16H8V8Z"></path></svg> <?php echo $wo['lang']['generate_using_ai']; ?>
                                        <input type="hidden" name="ai_post" value="off" id="isAiAvatar">
                                    </a>
                                </li>
                            <?php } ?>
                            <?php if ($wo['user_profile']['avatar_org'] != $wo['userDefaultAvatar'] && $wo['user_profile']['avatar_org'] != $wo['userDefaultFAvatar']) {?>
                                <li>
                                    <a class="pointer" onclick="OpenCropModal()">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" class="hover_path" d="M19 17h3v2h-3v3h-2v-3H6a1 1 0 0 1-1-1V7H2V5h3V2h2v3h11a1 1 0 0 1 1 1v11z"></path><path fill="currentColor" d="M15 17v2H6a1 1 0 0 1-1-1V7H2V5h3V2h2v15h8zm2 5V7H9V5h9a1 1 0 0 1 1 1v11h3v2h-3v3h-2z"></path></svg> <?php echo $wo['lang']['crop_your_avatar']; ?>
                                    </a>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                    <div class="avatar_cover_wrapper">
                        <svg class="avatar_cover_svg" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M14,6L10.25,11L13.1,14.8L11.5,16C9.81,13.75 7,10 7,10L1,18H23L14,6Z" /></svg>
                    </div>
                  <img class="group_avatar" src="<?php echo $wo['setting']['avatar'];?>" alt="Picture">
                </span>
                <input type="file" class="hidden" id="avatar" accept="image/x-png, image/gif, image/jpeg" name="avatar">
            </div>
            <div class="avatar-read" id="photo-form"><p></p></div>
        </div>
		<div class="text-center">
			<button class="btn btn-main btn-mat btn-mat-raised disable_btn" type="submit"><?php echo $wo['lang']['save']; ?></button>
		</div>
		<input type="hidden" name="page_id" id="page-id" value="<?php echo $wo['setting']['page_id'];?>">
		<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
	</form>
</div>

<div class="modal fade" id="cover_prompt_modal" role="dialog" data-keyboard="false">
    <div class="modal-dialog modal-md wow_mat_mdl">
        <div class="modal-content">
            <div class="modal-header">
                <p style="font-weight: bold">
                    <?php echo $wo["lang"]["add_cover"]?>
                </p>
            </div>
            <div class="modal-body">
                <div class="cover_modal_img">
                    <img src="<?php echo $wo['config']['theme_url'];?>/img/select-message.png" alt="">
                </div>
                <div class="cover_prompt_label">
                    <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                        <path fill="rgb(42, 88, 133)" d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
                    </svg>
                    <p class="cover_prompt_blue"><?php echo $wo['lang']['upload_cover']?></p>
                    <p class='cover_prompt'><?php echo $wo['lang']['cover_prompt']?></p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-mat close_cover_modal"><?php echo $wo['lang']['close'] ?></button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="cropImage" role="dialog">
    <div class="modal-dialog wow_mat_mdl modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><?php echo $wo['lang']['crop_your_avatar'] ?></h4>
            </div>
            <div class="modal-body">
                <div id="image-to-crop" class="wo_crop_img_pic">
                    <img src="<?php echo Wo_GetMedia($wo['setting']['avatar_full'])?>" alt="avatar" data-image="<?php echo $wo['setting']['avatar_full']; ?>" >
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-mat disable_btn" data-dismiss="modal" aria-label="Close"><?php echo $wo['lang']['cancel'] ?></button>
                <button type="button" class="btn btn-main btn-mat disable_btn" onclick="CropImage();"><?php echo $wo['lang']['save']; ?></button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

$(".cover_modal_trigger").on('click', function(e) {
	e.preventDefault()
	console.log($('#cover_prompt_modal'))
	$('#cover_prompt_modal').toggleClass("show")
}) 

$(".close_cover_modal").on('click', function(e) {
	$('#cover_prompt_modal').removeClass("show")
}) 

$('.cover_prompt_label').on('click', function(e) {
	$('#cover_input').trigger("click")
}) 


function Wo_UpdateProfileCover() {
  $('#cover_prompt_modal').removeClass("show");
  $("form.profile-cover-changer").submit();
}

function OpenCropModal() {
    $('#cropImage').modal('show');
    setTimeout(function () {
        $('#image-to-crop img').rcrop({
            minSize : [130,130],
            preserveAspectRatio : true,
            grid : true,
        });
    }, 250);
}
function CropImage() {
    values = $('#image-to-crop img').rcrop('getValues');
    $path = $('#image-to-crop img').attr('data-image');
    if (!$path) {
        return false;
        $('#cropImage').modal('hide');
    }
    console.log(values, $path)

    var form_data = new FormData();
    form_data.append('path', $path);
    form_data.append('user_id', '<?php echo $wo['user']['user_id']; ?>');
    form_data.append('x', values.x);
    form_data.append('y', values.y);
    form_data.append('width', values.width);
    form_data.append('height', values.height);

    jQuery.ajax({
        url: Wo_Ajax_Requests_File() + '?f=crop-avatar&s=group',
        method: "post",
        dataType: 'json',
        data: form_data,
        processData: false, contentType: false,
        beforeSend: () => {$('.user-avatar-uploading-container').fadeIn(200);},
        success: (data) => {
            if (data.status == 200) {
                location.reload(false);
            } else {
                $('#cropImage').modal('hide');
            }
            console.log(data);
        }});
    $('#cropImage').find('.disable_btn').attr('disabled','disabled');
    //$.post(Wo_Ajax_Requests_File() + '?f=crop-avatar', {user_id:<?php //echo $wo['user_profile']['id']; ?>//, path: $path, x: values.x, y:values.y, height: values.height, width:values.width}, function(data, textStatus, xhr) {
    //    if (data.status == 200) {
    //        location.reload(false);
    //    } else {
    //        $('#cropImage').modal('hide');
    //    }
    //    $('#cropImage').find('.disable_btn').removeAttr("disabled");
    //});
}


$(document).ready(function() {
	$("#cover").on('change', function() {
	//Get count of selected files
	$("#coverimage-holder").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'>");
	});
});

$(document).ready(function() {
    $("#avatar").on('change', function() {
        //Get count of selected files
    $(".setting-profile-form").trigger("submit")
    $("#avatarimage-holder").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'>");
    });
});

$(function() {
    //Изменение обложки
    $('.profile-cover-changer').ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=pages&s=update_images_setting',

        beforeSend: function () {
            $('.profile_cover').fadeOut(100);
            $('.user-cover-uploading-container,.user-cover-uploading-progress').fadeIn(200);
        },
        success: function (data) {
            $('.profile_cover').fadeIn(100);
            if(data.status == 200) {
                $('[id^=cover-image]').attr('data-target', '#ProfileCoverImageModal-Stopped');
                $('[id^=cover-image]').attr('onclick', 'Wo_OpenProfileCover("' + data.cover_or + '");');
                $('[id^=cover-image]').attr("src", data.img);
                $('#full-image').attr("src", data.cover_full);
                $('#full-input-image').val(data.cover_full);
                $('#cover-input-image').val(data.cover_or);
                Wo_StartRepositioner();
            } else {
                if(data.invalid_file == 3){
                    $("body").snackbar({
                        message: "<?php echo $wo['lang']['adult_image_file']; ?>"
                    });
                }
            }
            $('.user-cover-uploading-container,.user-cover-uploading-progress').fadeOut(200);
        }
    });

    //Позиционирование обложки
    $('form.cover-position-form').ajaxForm({
        url:  Wo_Ajax_Requests_File() + '?f=re_cover',
        dataType:  'json',
        beforeSend: function() {
            $('.user-reposition-dragable-container').hide();
            $('.user-repositioning-icons-container').html('<div class="pace-activity-parent"><div class="pace-activity"></div></div>').fadeIn('fast');
        },
        success: function(data) {
            if (data.status == 200) {
                $('.user-cover-reposition-w img').attr('src', data.url + '?time=' + Math.random()).on("load", function () {
                    $('.when-edit').hide();
                    $('.when-notedit').show();
                    $('.user-repositioning-icons-container').fadeOut('fast').html('');
                    $('.user-cover-reposition-w').show();
                    $('.user-reposition-container').hide().find('img').css('top', 0);
                    $('.cover-resize-buttons').hide();
                    $('.default-buttons').show();
                    $('input.cover-position').val(0);
                    $('.wo_user_profile .card.hovercard .pic-info-cont, .problackback').fadeIn();
                });
            }
        }
    });

    $("#cover").change(function() {
        var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
        $("#cover-form p").html(filename);
        $("#cover-form").fadeIn(200);
    });
    
    $('form.setting-profile-form').ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=pages&s=update_images_setting',
        beforeSend: function() {
        $('.setting-profile-form').find('.disable_btn').attr('disabled','disabled');
        },
        success: function(data) {
        if (data.status == 200) {
            scrollToTop();
            if (data.avatar) {
                var page_id = $('form.setting-profile-form').find('#group-id').val();
                $('[id^=updatePageImage-' + page_id + ']').fadeOut(300, function () { $('[id^=updateGroupImage-' + page_id + ']').attr("src", data.avatar)}).fadeIn(300);
                $('#cropImage').modal('show');
                $('#image-to-crop img').attr('src', data.avatar_full);
                $('#image-to-crop img').attr('data-image', data.avatar_full_or);
                $('#image-to-crop img').on("load", function() {
                    setTimeout(function () {
                        $('#image-to-crop img').rcrop({
                            minSize : [130,130],
                            preserveAspectRatio : true,
                            grid : true
                        });
                    }, 1000);
                }).each(function() {
                    if(this.complete) $(this).load();
                });
            }
            if (data.cover) {
            $('[id^=cover-image]').fadeOut(300, function () { $('[id^=cover-image]').attr("src", data.cover)}).fadeIn(300);
            }
            $('.setting-profile-alert').html('<div class="alert alert-success">' + data.message + '</div>');
            $('.alert-success').fadeIn('fast', function() {
            $(this).delay(2500).slideUp(500, function() {
                $(this).remove();
            });
            });
        } 
        $('.setting-profile-form').find('.disable_btn').removeAttr("disabled");
        }
    });
});
</script>