<?php 
$wondertage_settings = array();
if (mysqli_query($wo['sqlConnect'], "DESCRIBE `wondertage_settings`" )) {
	$settings = $db->get('wondertage_settings');
	foreach ($settings as $key => $value) {
		$wondertage_settings[$value->name] = $value->value;
	}
}
?>

<?php if (!empty($wondertage_settings) && $wondertage_settings['tag_artplayer'] == 1) { ?>
	<div class="embed-responsive embed-responsive-16by9">
		<div class="artplayer-app" id="video--<?php echo $wo['media']['storyId'];?>"></div>
	</div>

	<script>
	var art = new Artplayer({
		container: '#video--<?php echo $wo['media']['storyId'];?>',
		url: '<?php echo $wo['media']['filename'];?>',
		whitelist: ['*'],
		customType: {
			m3u8: function(video, url) {
				var hls = new Hls();
				hls.loadSource(url);
				hls.attachMedia(video);
				if (!video.src) {
					video.src = url;
				}
			},
		},
		poster: '<?php  echo $wo['media']['video_thumb'];?>',
		volume: 1,
		isLive: true,
		pip: true,
		fullscreen: true,
		theme: '<?php echo $wo['config']['btn_background_color'];?>',
		icons: {
			state: '<svg class="playback-icons" xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path fill="currentColor" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 13.5v-7c0-.41.47-.65.8-.4l4.67 3.5c.27.2.27.6 0 .8l-4.67 3.5c-.33.25-.8.01-.8-.4z"/></svg>',
		},
	});

	art.on('ready', function() {
		$('#video--<?php echo $wo['media']['storyId'];?>').addClass('hide_control');
		$('.art-notice, .art-contextmenus').remove();
	});
	art.on('play', function() {
		Wo_AddVideoViews(<?php echo $wo['media']['storyId'];?>);
		$('#video--<?php echo $wo['media']['storyId'];?> .art-mask').remove();
		$('#video--<?php echo $wo['media']['storyId'];?>').removeClass('hide_control');
	});
	art.on('pause', function() {
		$('#video--<?php echo $wo['media']['storyId'];?>').addClass('show_control');
	});
	</script>
<?php } else { ?>
	<div class="tag_vid_plyr">
		<?php if ($wo['config']['cloudflare_stream']) { ?> 
			<div style="position: relative; padding-top: 56.25%;">
				<iframe class="video" src="<?php echo $wo['config']['base_url_cloudflare'];?>/<?php echo $wo['media']['video_thumb'];?>/iframe?poster=<?php echo $wo['config']['base_url_cloudflare'];?>/<?php echo $wo['media']['video_thumb'];?>/thumbnails%2Fthumbnail.jpg%3Ftime%3D%26height%3D600" 
                style="border: none; position: absolute; top: 0; left: 0; height: 100%; width: 100%;" 
                allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;" 
                allowfullscreen="true"></iframe>
			</div>
            
            
			<div id="converted_status"></div>
		<?php } else { ?>
			<video id="video--<?php echo $wo['media']['storyId'];?>"  class="plyrr-<?php echo $wo['media']['storyId'];?> <?php echo($wo['rvad_con']); ?>" playsinline preload="metadata" poster="<?php  echo $wo['media']['video_thumb'];?>" data-setup="{}" data-post-video="<?php echo $wo['media']['storyId'];?>"></video>
		<?php } ?>
	</div>

	<script crossorigin="anonymous" type="text/javascript">
    //  $(document).ready(function() {
    //     let observer = new IntersectionObserver(entries => {
    //         entries.forEach(entry => {
    //         if (entry.isIntersecting) {
    //             entry.target.contentWindow.postMessage('play', '*');
    //         } else {
    //             entry.target.contentWindow.postMessage('pause', '*');
    //         }
    //         });
    //     });

    //     $(".video").each(function() {
    //         observer.observe(this);
    //     });
    //     });
	 async function getVideoDetails(videoId) {
    	const apiKey = "<?php echo $wo['config']['bearer_cloudflare'] ?>";
		const account_id = "<?php echo $wo['config']['account_id_cloudflare'] ?>";
		fetch(`https://api.cloudflare.com/client/v4/accounts/${account_id}/stream?search=${videoId}`, {
        method: "GET",
        headers: {
            "Authorization": `Bearer ${apiKey}`,
            "Content-Type": "application/json"
        }
        })
        .then(response => response.json())
        .then(data => {
			let status = data.result[0].status.state; 

			if (status != 'ready') {
				console.log(data.result[0].status.state);
				$( "#converted_status" ).append( "<span style='background: #eee;position: absolute;margin-top: -589px;overflow: visible; width:650px;height:600px'><img style='margin-top: 350px;margin-left: 250px;' src='<?php echo $wo['config']['theme_url'] ?>/img/pngegg.png' alt='' width='128' height='128'></span>" );
			} 
			
		})
        .catch(error => console.log(error));
	}

	getVideoDetails('<?php echo $wo['media']['video_thumb'];?>');

	var source = '<?php echo $wo['media']['filename'];?>';
	
	var tagvideo = '.plyrr-<?php echo $wo['story']['id'];?>';
	var players = Plyr.setup(tagvideo, {
		controls: ['play-large', 'progress', 'play', 'mute', 'volume', 'current-time', 'pip', 'airplay', 'fullscreen'],
		<?php if (Wo_IsMobile() == false) { ?>
		ratio: '16:9',
		<?php } ?>
		fullscreen: {
			iosNative: true
		},
		ads: {
			enabled: false,
			tagUrl: ''
		}
	});

	// if (!Hls.isSupported()) {
	// 	tagvideo.src = source;
	// } else {
	// 	const hls = new Hls();
	// 	hls.loadSource(source);
	// 	hls.attachMedia(tagvideo);
	// 	window.hls = hls;
	// }

	$(window).scroll(function(e){
		if (!document.pictureInPictureElement) {
			$('.plyrr-<?php echo $wo['story']['id'];?>').each(function(){
				if ($(this).is(":in-viewport")) {
					
				} else {
					$(this)[0].pause();
				}
			});
		}

        
	});
	</script>
<?php } ?>