<label class="tag_field">
    <?php
    if ($wo['field']['select_type'] == 'yes') {
        $options = @explode(',', $wo['field']['type']); ?>
        <select name="<?php echo $wo['field']['fid'];?>">
            <option value=""><?php echo $wo['lang']['none'];?></option>
            <?php foreach ($options as $key => $value) { ?>
                <option value="<?php echo $key + 1;?>"><?php echo $value;?></option>
            <?php } ?>
        </select>
    <?php } else { if ($wo['field']['type'] == 'textbox') { ?>
        <input id="<?php echo $wo['field']['fid'];?>" name="<?php echo $wo['field']['fid'];?>" placeholder=" " type="text">
    <?php } else if ($wo['field']['type'] == 'textarea') {?>
        <textarea id="<?php echo $wo['field']['fid'];?>" name="<?php echo $wo['field']['fid'];?>" placeholder=" " rows="3"></textarea>
    <?php } } ?>
    <span class="woodworking_label"><?php echo $wo['field']['name']; ?>
        <?php if($wo['field']['select_type'] == 'yes' && $wo['field']['id'] == "3") {
        echo $wo['lang']['in_woodworking'];
        } else {echo $wo['field']['description'];} ?></span>
</label>