<?php
function my_mb_ucfirst($str) {
    $fc = mb_strtoupper(mb_substr($str, 0, 1));
    return $fc.mb_substr($str, 1);
}
;?>

<style>
.required-field {
  color: red;
}
</style>
<div class="container">
	<div class="valign tag_startup">
		<div class="wow_content p20">
			<div class="row tag_startup_row">
				<div class="col-xl-4 col-lg-3">
					<?php if (Wo_IsMobile() == false) { ?>
					<div class="tag_startup_img">
						<h2 class="text-center tag_page_title"><?php echo $wo['lang']['tell_us']; ?></h2>
						<img src="<?php echo $wo['config']['theme_url'];?>/img/start_up/info.png" alt="<?php echo $wo['lang']['info']; ?>">
					</div>
					<?php } ?>
				</div>
				<div class="col-xl-8 col-lg-9">
					<ul class="list-unstyled tag_steps tag_startup_steps">
						<li class="active"><div><svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24" viewBox="0 0 24 24" width="24"><g><rect fill="none" height="24" width="24"/></g><g><path fill="currentColor" d="M19,3H5C3.9,3,3,3.9,3,5v14c0,1.1,0.9,2,2,2h14c1.1,0,2-0.9,2-2V5C21,3.9,20.1,3,19,3z M6.6,16.2l2-2.67 c0.2-0.27,0.6-0.27,0.8,0L11.25,16l2.6-3.47c0.2-0.27,0.6-0.27,0.8,0l2.75,3.67c0.25,0.33,0.01,0.8-0.4,0.8H7 C6.59,17,6.35,16.53,6.6,16.2z"/></g></svg> <span><?php echo $wo['lang']['ad_media']; ?></span></div></li>
						<li class="active"><div><svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24" viewBox="0 0 24 24" width="24"><g><path d="M0,0h24v24H0V0z" fill="none"/></g><g><path fill="currentColor" d="M12,2C6.48,2,2,6.48,2,12s4.48,10,10,10s10-4.48,10-10S17.52,2,12,2z M12,17c-0.55,0-1-0.45-1-1v-4c0-0.55,0.45-1,1-1 s1,0.45,1,1v4C13,16.55,12.55,17,12,17z M12,9L12,9c-0.55,0-1-0.45-1-1v0c0-0.55,0.45-1,1-1h0c0.55,0,1,0.45,1,1v0 C13,8.55,12.55,9,12,9z"/></g></svg> <span><?php echo $wo['lang']['info']; ?></span></div></li>
						<li><div><svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24" viewBox="0 0 24 24" width="24"><g><rect fill="none" height="24" width="24"/><rect fill="none" height="24" width="24"/></g><g><path fill="currentColor" d="M22,9V8c0-0.55-0.45-1-1-1h0c-0.55,0-1,0.45-1,1v1h-1c-0.55,0-1,0.45-1,1v0c0,0.55,0.45,1,1,1h1v1c0,0.55,0.45,1,1,1h0 c0.55,0,1-0.45,1-1v-1h1c0.55,0,1-0.45,1-1v0c0-0.55-0.45-1-1-1H22z"/><g><path fill="currentColor" d="M8,12c2.21,0,4-1.79,4-4s-1.79-4-4-4S4,5.79,4,8S5.79,12,8,12z"/><path fill="currentColor" d="M8,13c-2.67,0-8,1.34-8,4v3h16v-3C16,14.34,10.67,13,8,13z"/><path fill="currentColor" d="M12.51,4.05C13.43,5.11,14,6.49,14,8s-0.57,2.89-1.49,3.95C14.47,11.7,16,10.04,16,8S14.47,4.3,12.51,4.05z"/><path fill="currentColor" d="M16.53,13.83C17.42,14.66,18,15.7,18,17v3h2v-3C20,15.55,18.41,14.49,16.53,13.83z"/></g></g></svg> <span><?php echo $wo['lang']['follow']; ?></span></div></li>
					</ul>
					<hr>
					<div class="wow_usr_steps">
						<h4 class="text-center"><?php echo $wo['lang']['tell_us_des'];?></h4>
						<br>
						<form class="setting-general-form form-horizontal" method="post">
							<label class="tag_field">
								<input id="first_name" name="first_name" type="text" placeholder="" value="<?php echo $wo['user']['first_name']?>" required oninvalid="this.setCustomValidity('<?php echo $wo['lang']['wm_feild_required']; ?>')">
								<span><?php echo $wo['lang']['first_name']; ?> <span class="required-field">*</span></span>
							</label>
                            <label class="tag_field">
                                <input id="last_name" name="last_name" type="text" placeholder="" value="<?php echo $wo['user']['last_name']?>" required oninvalid="this.setCustomValidity('<?php echo $wo['lang']['wm_feild_required']; ?>')">
                                <span><?php echo $wo['lang']['last_name']; ?> <span class="required-field">*</span></span>
                            </label>
							<label class="tag_field">
								<input id="email" name="email" type="email" placeholder="" value="<?php echo $wo['user']['email']?>" required oninvalid="this.setCustomValidity('<?php echo $wo['lang']['wm_feild_required']; ?>')">
								<span><?php echo $wo['lang']['email']; ?> <span class="required-field">*</span></span>
							</label>
                            <div class="city_wrapper">
                                <label class="tag_field">
                                    <input id="city" name="city" type="text" placeholder="" value="<?php echo $wo["cities"][$wo['user']['country_id']]?>">
                                    <span><?php echo my_mb_ucfirst($wo['lang']['city']); ?></span>
                                </label>
                                <div class="themes_dropdown_body dropdown-menu">
                                    <ul>
                                        <li class="themes_dropdown_item none_selected" data-id="none"><?php echo $wo["lang"]["none_selected"]; ?></li>
                                        <?php foreach($wo["cities"] as $city_id => $city_name) { ?>
                                            <li class="themes_dropdown_item" data-id="<?= $city_id; ?>"><?= $city_name; ?></li>
                                        <?php }; ?>
                                    </ul>
                                </div>
                            </div>
<!--							<label class="tag_field">-->
<!--								<select id="country" name="country">-->
<!--									--><?php // pa($wo['user']); 
//										foreach ($wo['countries_name'] as $country_ids => $country) {
//										$country_id = $wo['user']['country_id'];
//										$selected_contry = ($country_ids == $country_id) ? ' selected' : '' ;
//									?>
<!--										<option value="--><?php //echo $country_ids;?><!--" --><?php //echo $selected_contry;?><!-- >--><?php //echo $country;?><!--</option>-->
<!--									--><?php //} ?>
<!--								</select>-->
<!--								<span>--><?php //echo $wo['lang']['country']; ?><!--</span>-->
<!--							</label>-->
							<?php
								$cutoff   = 1930;
								$now      = date('Y');
								$birthday = '';
								if ($wo['user']['birthday'] != '0000-00-00') {
									$birthday = explode('-', $wo['user']['birthday']);
								}
							?>
							<label class="tag_field">
								<input id="usr_birthday" name="birthday" type="text" placeholder=" ">
								<span><?php echo $wo['lang']['birthday']; ?></span>
							</label>
							<input type="hidden" name="user_id" value="<?php echo $wo['user']['user_id'];?>">
							<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
						</form>
						<div class="clear"></div>
					</div>
					<div class="valign wow_usr_steps_cont">
						<div class="error_message"></div>
						<button class="btn con-button btn-main btn-mat disable_btn" onclick="Wo_SubmitInfoForm();"><?php echo $wo['lang']['start_up_continue'];?></button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
$(function() {
	$("#usr_birthday").datepicker({
		changeMonth: true,
		changeYear: true,
		maxDate: new Date('2008-12-31'),
		dateFormat: 'dd-mm-yy',
		yearRange: "1893:2008",
		prevText: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M15.41,16.58L10.83,12L15.41,7.41L14,6L8,12L14,18L15.41,16.58Z" /></svg>',
		nextText: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M8.59,16.58L13.17,12L8.59,7.41L10,6L16,12L10,18L8.59,16.58Z" /></svg>'
	});
});

$("#city").on("click", function (e) {
    e.stopPropagation()
    $(".themes_dropdown_body").toggleClass("show")
})

$(".themes_dropdown_item").each((i, item) => {
    $(item).on("click", function (e) {
        e.stopPropagation()
        $("#city").val(this.textContent)
        $(".themes_dropdown_body").removeClass("show")
    })
})

$(document).on("click", function () {
    if($(".themes_dropdown_body").hasClass("show")) {
        $(".themes_dropdown_body").removeClass("show")
    }
})

function isEmail(email) {
  var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
  return regex.test(email);
}

function Wo_SubmitInfoForm() {
	var firstName = $("#first_name").val();
    var lastName = $("#last_name").val();
    var email = $("#email").val();
	
	if (firstName === "" || lastName === "" || email === "" || !isEmail(email)) {
	  if (firstName === "") {
		$("#first_name").focus();
		$("#first_name")[0].setCustomValidity("<?php echo $wo['lang']['wm_feild_required']; ?>");
		$("#first_name")[0].reportValidity();
	  } else if (lastName === "") {
		$("#last_name").focus();
		$("#last_name")[0].setCustomValidity("<?php echo $wo['lang']['wm_feild_required']; ?>");
		$("#last_name")[0].reportValidity();
	  }
	} else {	
		// Proceed with form submission if all fields are filled
		$("form.setting-general-form").submit();
	}
}
$(function () {
	$('form.setting-general-form').ajaxForm({
		url: Wo_Ajax_Requests_File() + '?f=update_user_information_startup',
		beforeSend: function () {
			$('button.disable_btn').attr('disabled', true);
			$('button.disable_btn').text("<?php echo $wo['lang']['please_wait'];?>");
		},
		success: function (data) {
			if(data.status == 200) {
				window.location.href = '<?php echo Wo_SeoLink('index.php?link1=start-up');?>';
			}
			if(data.status == 400) {
				$( ".error_message" ).append( $( 
					`<div class="alert alert-primary" role="alert">
						${data.errorMessage}
					</div>` ) );
				$('button.disable_btn').attr('disabled', false);
				$('button.disable_btn').text("<?php echo $wo['lang']['start_up_continue'];?>");
			}
		}
	});
});
</script>