<?php 
	$group_privacy = $wo['lang']['public'];
	if ($wo['group']['privacy'] == 2) {
		$group_privacy = $wo['lang']['private'];
	}
?>
<div class="col-xl-4 col-lg-6 col-md-6">
	<div class="wow_content wow_my_groups">

		<div class="home profile-style promoted-style sidebar-page-data wo_sidebar_pages group-sug" data-page-id="<?php echo $wo['group']['id']?>">
			<div class="card hovercard promoted">
				<div class="cardheader">
					<a href="<?php echo $wo['group']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['group']['username']?>">
						<img src="<?php echo $wo['group']['cover']?>" id="cover-image" alt="<?php echo $wo['group']['username']?> Cover Image">
					</a>
				</div>
				<div class="page_middle">
				<div class="avatar <?php echo Wo_RightToLeft('pull-left');?>">
					<img id="updateImage-<?php echo $wo['group']['id']?>" alt="<?php echo $wo['group']['username']?> Profile Picture" src="<?php echo $wo['group']['avatar']?>">
				</div>
				<div class="info ">
					<div class="title">
						<span class="user-popover" data-id="<?php echo $wo['group']['id'];?>" data-type="<?php echo $wo['group']['type'];?>">
						<a id="user-full-name" href="<?php echo $wo['group']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['group']['username']?>"><?php echo $wo['group']['group_title'];?></a>  <?php if ($wo['group']['verified'] == 1) { ?> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="verified-color feather feather-check-circle" title="<?php echo $wo['lang']['verified_user'];?>" data-toggle="tooltip" style="vertical-align: unset;"><path d="M23,12L20.56,9.22L20.9,5.54L17.29,4.72L15.4,1.54L12,3L8.6,1.54L6.71,4.72L3.1,5.53L3.44,9.21L1,12L3.44,14.78L3.1,18.47L6.71,19.29L8.6,22.47L12,21L15.4,22.46L17.29,19.28L20.9,18.46L20.56,14.78L23,12M10,17L6,13L7.41,11.59L10,14.17L16.59,7.58L18,9L10,17Z" /></svg> <?php } ?>
						</span>
					</div>
					<div class="page_catg text-muted" style="font-size: 12px;"><?php echo $wo['group']['category']?></div>
					<div class="text-muted" style="font-size: 12px;">
						<?php echo $wo['lang']['members'];?>: <?php echo Wo_CountGroupMembers($wo['group']['id']);?>
					</div>
				</div>
				</div>
				<div class="user-follow-button">
					<?php if( isset( $wo['group']['Wo_GroupSug'] ) ){ ?>
						<?php echo Wo_GetJoinButton($wo['group']['id']);?>
					<?php }else{ ?>
						<a href="<?php echo Wo_SeoLink('index.php?link1=group-setting&group=' .  $wo['group']['group_name']); ?>" data-ajax="?link1=group-setting&group=<?php echo $wo['group']['group_name'];?>" class="btn btn-default btn-mat"><?php echo $wo['lang']['edit']; ?></a>
					<?php } ?>
				</div>
			</div>
		</div>
		
	</div>
</div>

<style>
.wo_sidebar_pages .user-follow-button .btn {
	margin: 10px 7px;
	width: calc(100% - 14px);
	border-radius: 8px !important;
	line-height: 30px;
}
.wo_sidebar_pages .card {
    position: relative;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-direction: column;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: none;
    border-radius: 1.25rem;
}
.group-sug {
    padding: 0px;
}
.wow_my_groups .avatar img {
	position: inherit;
}
</style>