<div class="page-margin">
	<div class="container">
		<h2 class="tag_page_title m5"><?php echo $wo['lang']['events']; ?></h2>
		<ul class="list-unstyled tag_page_nav">
			<?php if ($wo['config']['can_use_events']) { ?>
				<li class="separate <?php echo ($wo['active'] == "7" ? "active" : "")?>"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=my-events'); ?>" data-ajax="?link1=my-events"><?php echo $wo['lang']['my_events']; ?></a></li>
			<?php } ?>
			<li class="<?php echo ($wo['active'] == "1" ? "active" : "")?>"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=events'); ?>" data-ajax="?link1=events"><?php echo $wo['lang']['browse_events'] ?></a></li>
			<li class="<?php echo ($wo['active'] == "2" ? "active" : "")?>"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=events-going'); ?>" data-ajax="?link1=events-going"><?php echo $wo['lang']['event_going']; ?>	</a></li>
			<li class="<?php echo ($wo['active'] == "3" ? "active" : "")?>"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=events-invited'); ?>" data-ajax="?link1=events-invited"><?php echo $wo['lang']['event_invited']; ?></a></li>
			<li class="<?php echo ($wo['active'] == "4" ? "active" : "")?>"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=events-interested'); ?>" data-ajax="?link1=events-interested"><?php echo $wo['lang']['event_intersted']; ?></a></li>
			<li class="<?php echo ($wo['active'] == "5" ? "active" : "")?>"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=events-past'); ?>" data-ajax="?link1=events-past"><?php echo $wo['lang']['events_past']; ?></a></li>
		</ul>
		<div class="page-margin wow_content wow_sett_content">
			<div class="valign wo_page_hdng">
				<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M19 19V8H5V19H19M16 1H18V3H19C20.11 3 21 3.9 21 5V19C21 20.11 20.11 21 19 21H5C3.89 21 3 20.1 3 19V5C3 3.89 3.89 3 5 3H6V1H8V3H16V1M11 9.5H13V12.5H16V14.5H13V17.5H11V14.5H8V12.5H11V9.5Z"></path></svg></span> <?php echo $wo['lang']['create_events'];?>
			</div>
			<form class="form form-horizontal" method="post" id="insert-event">
				<div class="row">
					<div class="col-xl-5">
						<div class="tag_alone_label">
							<label><?php echo $wo['lang']['select_image']; ?></label>
						</div>
						<div class="wow_fcov_image crt_eve_image">
							<div id="wow_fcov_img_holder"></div>
							<div class="valign upload_ad_image" onclick="document.getElementById('event-cover').click(); return false">
								<div class="btn btn-mat btn-default upload_ad_image_content">
									<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M8.5,13.5L11,16.5L14.5,12L19,18H5M21,19V5C21,3.89 20.1,3 19,3H5A2,2 0 0,0 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19Z"></path></svg> <?php echo $wo['lang']['choose_image'] ?>
								</div>
							</div>
						</div>
						<p>
							<?php echo $wo['lang']['prompt_on_create_cover_page']?>
						</p>
					</div>
					<div class="col-xl-7">
						<label class="tag_field">
							<input id="event-name" name="event-name" type="text" placeholder=" ">
							<span><?php echo $wo['lang']['event_name']; ?></span>
						</label>
						<label class="tag_field">
							<textarea name="event-description" id="event-description" placeholder=" " rows="5"></textarea>
							<span><?php echo $wo['lang']['event_desc']; ?></span>
						</label>
						
						<label class="tag_field">
							<input id="event-organizer-name" name="event-organizer-name" type="text" placeholder=" ">
							<span><?php echo $wo['lang']['event_organizer_name']; ?></span>
						</label>
						<label class="tag_field">
							<input id="event-organizer-link" name="event-organizer-link" type="text" placeholder=" ">
							<span><?php echo $wo['lang']['event_organizer_link']; ?></span>
						</label>
						<label class="tag_field">
							<textarea name="event-organizer-contact" id="event-organizer-contact" placeholder=" " rows="5"></textarea>
							<span><?php echo $wo['lang']['event_organizer_contact']; ?></span>
						</label>
						<div class="">
							<label class="tag_field">
								<select name="event_category">
									<option value=""><?php echo $wo['lang']['none'];?></option>
									<?php foreach ($wo['blog_categories'] as $key => $value) { ?>
										<option value="<?php echo $value['id'];?>"><?= $wo['lang'][$value['lang_key']];?></option>
									<?php } ?>
								</select>
								<span><?=$wo['lang']['events_category_title']?></span>
							</label>
							<label class="tag_field">
								<select name="event_city">
									<option value=""><?php echo $wo['lang']['none'];?></option>
									<?php foreach ($wo['cities'] as $key => $value) { 
										$event_lang_key = Wo_GetLangOne($value['lang_key'])['lang_key'];
										if(!empty($event_lang_key)) {
									?>
										<option value="<?php echo $value['id'];?>"><?=$wo['lang'][$event_lang_key];?></option>
									<?php } } ?>
								</select>
								<span><?php echo $wo['lang']['located_in']; ?></span>
							</label>
						</div>
						
						
						<label class="tag_field">
							<div id="map"></div>
							<!-- <div id="search-box"></div> -->
							
							<label class="tag_field">
								<input id="event-locat" name="event-locat" type="text" placeholder="<?=$wo['lang']['location']?>">
							</label>
						
							<div id="result"></div>
							<div class="tag_alone_label">
								<label style="margin-top: -155px;margin-bottom: 47px;"><?php echo $wo['lang']['location']; ?></label>
							</div>
						</label>
						<?php if ($wo['config']['google_map'] == 1 || $wo['config']['yandex_map'] == 1) { ?>
							<div id="review-location">
								<div id="place" <?php echo($wo['config']['yandex_map'] == 1 ? 'class="yandex_ads_map"' : '') ?>></div>
							</div>
						<?php } ?>
						<div class="tag_alone_label">
							<label><?php echo $wo['lang']['event_start']; ?></label>
						</div>
						<div class="row">
							<div class="col-lg-6">
								<label class="tag_field">
									<input type="text" class="date" id="event-start" name="event-start-date" autocomplete="off" placeholder=" ">
									<span><?php echo $wo['lang']['start_date']; ?></span>
								</label>
							</div>
							<div class="col-lg-6">
								<label class="tag_field">
									<input type="text" id="event-start-time" class="time1" name="event-start-time" autocomplete="off" placeholder=" ">
									<span><?php echo $wo['lang']['start_time']; ?></span>
								</label>
							</div>
						</div>
						<div class="tag_alone_label">
							<label><?php echo $wo['lang']['event_end']; ?></label>
						</div>
						<div class="row">
							<div class="col-lg-6">
								<label class="tag_field">
									<input type="text" class="date1" name="event-end-date" id="event-end-date" autocomplete="off" placeholder=" ">
									<span><?php echo $wo['lang']['end_date']; ?></span>
								</label>
							</div>
							<div class="col-lg-6">
								<label class="tag_field">
									<input type="text" id="event-end-time" class="time1" name="event-end-time" autocomplete="off" placeholder=" ">
									<span><?php echo $wo['lang']['end_time']; ?></span>
								</label>
							</div>
						</div>
						<div class="setting-update-alert" id="event-alert"></div>
						<div class="text-center">
							<a class="btn btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=my-events'); ?>" data-ajax="?link1=my-events">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z"></path></svg> <?php echo $wo['lang']['go_back'];?>
							</a>
							<button class="btn btn-main btn-mat btn-mat-raised disable_btn" type="submit"><?php echo $wo['lang']['publish']; ?></button>
						</div>
					</div>
				</div>
				<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
				<input type="file" name="event-cover" class="hidden" id="event-cover" accept="image/*">
			</form>
		</div>
	</div>
</div>

<script src="https://cdn.jsdelivr.net/npm/jquery-ui-timepicker-addon@1.6.3/dist/jquery-ui-timepicker-addon.min.js"></script>
<script>
	$('.ui_tpicker_time_input').prop("disabled", false);

	
	<?php if ($wo['config']['google_map'] == 1) { ?>
      	$(document).on('change', '#event-locat', function(event) {
	        if ($(this).val().length >= 3) {
	          $("#review-location #place").html('<iframe width="100%" frameborder="0" src="https://www.google.com/maps/embed/v1/place?key=<?php echo $wo['config']['google_map_api']; ?>&q=' + $("#event-locat").val() + '&language=en"></iframe><br><br>')
	        }else{
	          $("#review-location #place").html('<iframe width="100%" frameborder="0" src="https://www.google.com/maps/embed/v1/place?key=<?php echo $wo['config']['google_map_api']; ?>&q=us&language=en"></iframe><br><br>')
	        }
      	});
     <?php } ?>
	 <?php if ($wo['config']['yandex_map'] == 1) { ?>
		 	$(document).on('change', '#event-locat', function(event) {
		   	var myMap;
		    ymaps.geocode($(this).val()).then(function (res) {
		    	$("#review-location #place").html('');
		        myMap = new ymaps.Map('place', {
		            center: res.geoObjects.get(0).geometry.getCoordinates(),
		            zoom : 10
		        });
		        myMap.geoObjects.add(new ymaps.Placemark(res.geoObjects.get(0).geometry.getCoordinates(), {
		            balloonContent: ''
		        }));
		    });
		 	});

		 <?php } ?>
	 
  jQuery(document).ready(function($) {
	
// Initialize an empty map without layers (invisible map)
        var map = L.map('map', {
            center: [40.7259, -73.9805], // Map loads with this location as center
            zoom: 12,
            scrollWheelZoom: true,
            zoomControl: false,
            attributionControl: false,
        });
        
        //Geocoder options
        var geocoderControlOptions = {
            bounds: false,          //To not send viewbox
            markers: false,         //To not add markers when we geocoder
            attribution: null,      //No need of attribution since we are not using maps
            expanded: true,         //The geocoder search box will be initialized in expanded mode
            panToPoint: false,       //Since no maps, no need to pan the map to the geocoded-selected location
            params: {               //Set dedupe parameter to remove duplicate results from Autocomplete
                    dedupe: 1,
                }
        }

        //Initialize the geocoder
        var geocoderControl = new L.control.geocoder('pk.5ad46c4b9ccd0c4096b6ee9cae3bd3a6', geocoderControlOptions).addTo(map).on('select', function (e) {
            displayLatLon(e.feature.feature.display_name, e.latlng.lat, e.latlng.lng);
        });

        //Get the "search-box" div
        var searchBoxControl = document.getElementById("search-box");
        //Get the geocoder container from the leaflet map
        var geocoderContainer = geocoderControl.getContainer();
        //Append the geocoder container to the "search-box" div
        // searchBoxControl.appendChild(geocoderContainer);        

        //Displays the geocoding response in the "result" div
        function displayLatLon(display_name, lat, lng) {
            var resultString = "You have selected " + display_name + "<br/>Lat: " + lat + "<br/>Lon: " + lng;
            ///document.getElementById("result").innerHTML = resultString;
			document.getElementById("event-locat").value = display_name;
			//$("event-locat").trigger('change');
			$("#review-location #place").html('<iframe width="100%" frameborder="0" src="https://www.google.com/maps/embed/v1/place?key=<?php echo $wo['config']['google_map_api']; ?>&q=' + $("#event-locat").val() + '&language=en"></iframe><br><br>');
        }



	<?php if ($_SESSION["lang"] == "russian"){ ?>
		$.timepicker.regional['ru'] = {
			timeOnlyTitle: 'Выберите время',
			timeText: 'Время',
			hourText: 'Часы',
			minuteText: 'Минуты',
			secondText: 'Секунды',
			millisecText: 'Миллисекунды',
			timezoneText: 'Часовой пояс',
			currentText: 'Сейчас',
			closeText: 'Закрыть',
			timeFormat: 'HH:mm',
			amNames: ['AM', 'A'],
			pmNames: ['PM', 'P'],
			isRTL: false,
			disabled: false,
		};
		$.timepicker.setDefaults($.timepicker.regional['ru']);
	<?php } ?>
      $( ".date" ).datepicker({ dateFormat: 'yy-mm-dd', minDate: 'today'});
      $( ".date1" ).datepicker({ dateFormat: 'yy-mm-dd', minDate: '+1day'});
      $( ".time1" ).timepicker();

      $("#event-cover").change(function(event) {
        $("#wow_fcov_img_holder").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'>")
      });

      $('#insert-event').ajaxForm({
            url: Wo_Ajax_Requests_File() + '?f=insert-event',
            beforeSend: function() {
			  $('#insert-event').find('.disable_btn').attr('disabled','disabled');
            },
            success: function(data) {
              if (data['status'] == 200) {
                $("#event-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
                window.location = data['url'];
              }
              else if (data['message']) {
                $("#event-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
              } 
			  $('#insert-event').find('.disable_btn').removeAttr("disabled");
            }
      });
  });
</script>