<?php if (Wo_IsMobile() == false) { ?>
<style>
.inner-but-full {
  margin-left: calc(-50vw + 50%);
  margin-right: calc(-50vw + 40%);
  height: auto;
  background:black;
}
.logo{
  margin-left:12%;
  max-width: 100%;
  height: auto;
}
.pull-right{
    margin-top:.3%;
    margin-right:18%;
    
}
img.one {
  height: auto;
  width: 100%;
  padding-top: 10px;
  padding-bottom: 10px;
}
</style>
<?php }else{ ?>
<style>
.inner-but-full {
  margin-left: calc(-50vw + 50%);
  margin-right: calc(-50vw + 50%);
  height: auto;
  background:black;
}
.logo{
  margin-left:1%!important;
  width: 5px!important;
  height: auto;
}
.pull-right{
    margin-top:1%;
    margin-right:1%;
    
}
img.one {
  height: auto;
  width: 100%;
  padding-top: 10px;
  padding-bottom: 10px;
}
</style>

<?php }?>
<div class="container">
	<div class="inner-but-full">
		<a class="logo" href="<?php echo $wo['config']['site_url'];?>"><img style="max-width: 140px !important; max-height: 50px !important" class="one" src="<?php echo $wo['config']['theme_url'];?>/img/logo.<?php echo $wo['config']['logo_extension'];?>" alt="Logo"> </a>
		
			<a class="btn btn-main btn-mat pull-right" href="<?php echo Wo_SeoLink('index.php?link1=welcome');?>"><?php echo $wo['lang']['login']?></a>
	
	</div>
</div>