<div id="city_dropdown" class="tag_srch_fltr_country dropdown post_themes_dropdown dropdown_categories">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12,11.5A2.5,2.5 0 0,1 9.5,9A2.5,2.5 0 0,1 12,6.5A2.5,2.5 0 0,1 14.5,9A2.5,2.5 0 0,1 12,11.5M12,2A7,7 0 0,0 5,9C5,14.25 12,22 12,22C12,22 19,14.25 19,9A7,7 0 0,0 12,2Z"></path></svg>
    <!--svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M3,3H11V7.34L16.66,1.69L22.31,7.34L16.66,13H21V21H13V13H16.66L11,7.34V11H3V3M3,13H11V21H3V13Z" /></svg-->
    <div class="d-flex align-items-center category_dropdown_header" data-original-title="<?= $wo['lang']['city_of_residence']; ?>" data-toggle="tooltip" data-placement="bottom">                                    
        <span><?=$wo['lang']['located_in']?></span>
        <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" fill="currentColor" class="bi bi-caret-down-fill" viewBox="0 0 16 16">
            <path d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
        </svg>
    </div>
    <div class="themes_dropdown_body dropdown-menu">
        <!-- <p class="dropdown-menu_desc">
        </p> -->
        <ul>
            <li class="themes_dropdown_item none_selected"><?php echo $wo["lang"]["none_selected"]; ?></li>
            <?php foreach($wo['cities'] as $city_id => $city) { ?>
                <li class="themes_dropdown_item" data-id="<?= $city['id']; ?>"><?= $city['city']; ?></li>
            <?php }; ?>
        </ul>
    </div>
</div>
<input id="city_input" type="hidden" name="city" value="">

<script>
$(document).on('mouseup', function() {
	$("#city_dropdown .category_dropdown_header").removeClass("show")
})

$(document).ready(function() {

if(location.href.includes('search')) {
    $("#city_dropdown .themes_dropdown_item").each((i, item) => {
        $(item).on("click", function () {
            $('#city_input').val($(item).data('id'))
            if ("function" == typeof window.search) {
                search();
            }
        })
    })
}

//Если страница настроек в поле подставляются данные пользователя
if(location.href.includes('group-setting') || location.href.includes('page-setting')) {
    $("#city_dropdown .themes_dropdown_item").each((i, item) => {
        if(String($(item).data('id')) === '<?=$wo['setting']['geo_city_id']?>') {
            $("#city_dropdown .category_dropdown_header span").text($(item).text());
            $(item).addClass('active');
            $('#city_input').val($(item).data('id'));
        }
    })
} else if(location.href.includes('setting')) {  
    let urlUsername = location.href;
    let username = urlUsername.match('/setting/(.+)/general-setting');

    username = ((undefined !== username && null !== username) ? username[1] : false);

    if(username) {
        getUserApi(username).then((data) => {
            $("#city_dropdown .themes_dropdown_item").each((i, item) => {
                if(String($(item).data('id')) === data.user_data.city) {
                    $("#city_dropdown .category_dropdown_header span").text($(item).text())
                    $(item).addClass('active');
                    $('#city_input').val($(item).data('id'));
                }
            })
        })
    } else {
        if(location.href.includes('setting')) {
            $("#city_dropdown .themes_dropdown_item").each((i, item) => {
                if($(item).data('id') === <?=$wo['user']['city_id']?>) {
                    $("#city_dropdown .category_dropdown_header span").text($(item).text());
                    $(item).addClass('active');
                    $('#city_input').val($(item).data('id'));
                }
            })
        }
    }

}


$("#city_dropdown .category_dropdown_header").on("click", function (e) {
    e.stopPropagation()
    if($("#city_dropdown .themes_dropdown_body").hasClass("show")) {
        $("#city_dropdown .themes_dropdown_body").removeClass("show")
    } else {
        $("#city_dropdown .themes_dropdown_body").addClass("show")
    }
})

$("#city_dropdown .themes_dropdown_item").each((i, item) => {
    $(item).on("click", function () {
        console.log($(item).hasClass("none_selected"))
        if($(item).hasClass("none_selected")) {
            $("#city_dropdown .category_dropdown_header span").text('<?=$wo['lang']['located_in']?>')
        } else {
            $("#city_dropdown .category_dropdown_header span").text($(item).text())
        }

        $("#city_dropdown .themes_dropdown_item").each((index, category) => {
            $(category).removeClass('active')
        })
        if(!$(item).hasClass("active")) {
            $(item).addClass("active")
        }
        $("#city_dropdown .themes_dropdown_body").removeClass("show")

        $('#city_input').val($(item).data('id'))
    })
})
})
</script>