<?php
    $fields = Wo_GetUserCustomFields();
    if (count($fields) > 0) {
        unset($fields[1]);
        foreach ($fields as $key => $wo['field']) {
            $wo['field']['issearch'] = true;
            echo Wo_LoadPage('search/custom_select');
        }
    }
?>
<?php echo Wo_LoadPage('reusable_dropdown/countries_dropdown');?>
<?php echo Wo_LoadPage('reusable_dropdown/cities_dropdown');?>
<!-- <div class="tag_srch_fltr_country">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12,11.5A2.5,2.5 0 0,1 9.5,9A2.5,2.5 0 0,1 12,6.5A2.5,2.5 0 0,1 14.5,9A2.5,2.5 0 0,1 12,11.5M12,2A7,7 0 0,0 5,9C5,14.25 12,22 12,22C12,22 19,14.25 19,9A7,7 0 0,0 12,2Z" /></svg>
    <select name="country" id="country">
        <option value="" selected><?php echo $wo['lang']['country'];?></option>
        <?php 
            foreach ($wo['countries'] as $country_ids => $country) { 
        ?>
            <option value="<?= $country['id'];?>"><?= $country['country'];?></option>
        <?php } ?>
    </select>
    <span class="caret"></span>
</div>
<div class="tag_srch_fltr_country">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12,11.5A2.5,2.5 0 0,1 9.5,9A2.5,2.5 0 0,1 12,6.5A2.5,2.5 0 0,1 14.5,9A2.5,2.5 0 0,1 12,11.5M12,2A7,7 0 0,0 5,9C5,14.25 12,22 12,22C12,22 19,14.25 19,9A7,7 0 0,0 12,2Z" /></svg>
    <select name="city" id="city">
        <option value="" selected><?= $wo['lang']['located_in'];?></option>
        <?php 
            foreach ($wo['cities'] as $index => $city) { 
        ?>
            <option value="<?= $city['id'];?>"><?= $city['city'];?></option>
        <?php } ?>
    </select>
    <span class="caret"></span>
</div> -->