
<div class="container-fluid">
    <div>
        <h3>Manage Сities</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Manage Features</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Geo</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Manage Сities</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Add City</h6>
                    <div class="row">
                        <div class="col-md-12" style="margin-bottom:0;">
                            <div class=" add_city_form_alert"></div>
                            <form method="POST" id="add_city_form">
                                <input type="hidden" name="type" value="country">
                                <div class="row">
                                    <?php foreach (Wo_LangsNamesFromDB() as $wo['key_']){ ?>
                                    <div class="col-md-2" id="normal-query-form">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <label class="form-label"><?=ucfirst($wo['key_']);?></label>
                                                <input type="text" class="form-control" name="<?=$wo['key_'];?>">
                                            </div>
                                        </div>
                                    </div>
                                    <?php } ?>
                                    <div class="clearfix"></div>
                                    <div class="col-md-2">
                                        <div>&nbsp;</div>
                                        <button class="btn btn-info">Add</button>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-body">

                   <div><h6 class="card-title">Manage Сities</h6></div>
                   <div class="clearfix"></div>
                   <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr>
                                    <th><input type="checkbox" id="check-all" class="filled-in check-all" ><label for="check-all">ID</label></th>
                                    <!--th>Lang</th-->
                                    <th>Type</th>
                                    <th>City Name RU</th>
                                    <th>City Name EN</th>
                                    <!--th>Sort</th-->
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                ///* / ahilespelid  ///*/
                                foreach($wo["countries"] as $data){ //pa($data);
                                    $data['name'] = Wo_GetLangDetails($data['lang_key'])[0]['russian'] ?? '';
                                    $data['nameEN'] = Wo_GetLangDetails($data['lang_key'])[0]['english'] ?? '';
                                    $wo['city_id'] = $data['id'];
                                    $wo['city_data'] = $data;
                                	echo Wo_LoadAdminPage('geo_city/list');
                                }
                                ///*/ ahilespelid ///*/
                                ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="clearfix"></div>
                        <div class="row">
                            <div class="col-lg-3 col-md-3">
                                <span>&nbsp;</span>
                                <button type="button" class="btn btn-info waves-effect delete-selected d-block" disabled>Delete Selected<span></span></button>
                            </div>
                        </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->


<div class="modal fade" id="editcityModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal_content_back">
      <div class="modal-header">
        <h5 class="modal-title" id="editcityModalLabel">Edit City</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="edit_city_form_alert"></div>
        <form class="edit_city_lang" method="POST" id="modal-body-langs">
          <div class="data_lang"></div>
          <input type="hidden" name="hash_id" value="<?=Wo_CreateSession();?>">
          <input type="hidden" name="id_of_key" id="id_of_key" value="">
        </form>
        
      </div>
      <div class="modal-footer">
        
        <button type="button" class="btn btn-secondary modal_close_btn" data-dismiss="modal">CLOSE</button>
        <button type="button" class="btn btn-primary" id="save_edited_city">SAVE CHANGES</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModal1Label">Delete City?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this City?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Delete</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="SelectedDeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal1Label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModal1Label">Delete City?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure that you want to remove the selected City?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="DeleteSelected()" data-dismiss="modal">Submit</button>
            </div>
        </div>
    </div>
</div>
<script>
function update_sort_city(id, sort){
    $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_sort_geo', {id: id, sort: sort}, function(data, textStatus, xhr){
        if(data.status == 200){reload_page();}
    });    
}
function edit_city(id) {
  $('#id_of_key').val(id);
  $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=get_geo_langs', {lang_key: id}, function(data, textStatus, xhr) {
      if (data.status == 200) {
        $('.data_lang').html(data.html);
        $('#editcityModal').modal();
      }
  });
}
function DeleteSelected() {
    data = new Array();
    $('td input:checked').parents('tr').each(function () {
        data.push($(this).attr('data_selected'));
    });
    $('.delete-selected').attr('disabled', true);
    $('.delete-selected').text('Please wait..');
    $.post(Wo_Ajax_Requests_File()+'?f=admin_setting&s=remove_multi_geo&hash=' + $('.main_session').val(), {ids: data}, function () {
        $.each( data, function( index, value ){$('#list-' + value).remove();});
        $('.delete-selected').text('Delete Selected');
    });
}
///*/ ahilespelid ///*/
function Wo_DeleteCat(cat,type = 'show'){
    let id = cat.id;
    if (type == 'hide'){
        $('#DeleteModal').find('.btn-primary').attr('onclick', "Wo_DeleteCat('"+cat+"')");
        $('#DeleteModal').modal('show');
    return false;}
    
    $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=delete_geo&type='+cat.type+'&hash=' + $('.main_session').val(), cat, function(data, textStatus, xhr){
        //console.log(data);
        let el = $('#list-' + id);
        if(200 == data.status){
            el.fadeOut(300, function(){$(this).remove();});
        }else{
            el.animate({backgroundColor: 'red'}, 1000);
            el.animate({backgroundColor: 'none'}, 1000);
    }});
///*/ ahilespelid ///*/
}
function reload_page(){
    url = '?path=geo_country';
    $.post(Wo_Ajax_Requests_File_load() + url, {url:url}, function(data){
        $(".barloading").css("display","none");
        if($('#redirect_link')[0].hasAttribute("data-sent")){
            $('#redirect_link').attr('data-sent', "0");
        }
        json_data = JSON.parse($(data).filter('#json-data').val());
        $('.content').html(data);
        setTimeout(function(){
          $(".content").getNiceScroll().resize()
        }, 500);
        $(".content").animate({ scrollTop: 0 }, "slow");
    }); return ;                
}

$(document).ready(()=>{
    var add_city_form       = $('form#add_city_form');
    var edit_city_form      = $('form.edit_city_lang');
    var save_edited_city    = $('#save_edited_city');
    var del_city_form       = $('table .catdel');

    add_city_form.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=add_new_geo&hash=' + $('.main_session').val(),
        beforeSend: function(){add_city_form.find('.waves-effect').text("Please wait..");},
        success: function(data){
            if(data.status == 200){
                add_city_form.find('.waves-effect').text('Save');
                $('.add_city_form_alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> City successfully added</div>');
                setTimeout(function (){$('.add_city_form_alert').empty();}, 2000);                
                reload_page();
                //window.location.reload();
            }else{
                $('.add_city_form_alert').html('<div class="alert alert-danger"><i class="fa fa-check"></i> '+data.message+'</div>');
                setTimeout(function (){$('.add_city_form_alert').empty();}, 2000);
        }}
    });
    save_edited_city.on('click', function(e){
        e.preventDefault();
        
        $.ajax({
            url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_lang_key&hash=' + $('.main_session').val(),
            method: 'POST',
            data: edit_city_form.serialize(),
            beforeSend: function(){edit_city_form.find('.waves-effect').text("Please wait..");},
            success: function(data){
                if(data.status == 200){
                    edit_city_form.find('.waves-effect').text('Save');
                    $('.edit_city_form_alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> City successfully edited</div>');
                    setTimeout(function(){$('.edit_city_form_alert').empty();}, 3000);
                    console.log(edit_city_form.serialize());
                    
                    $('#editcityModal button.close')[0].click();
                    reload_page();
                    //window.location.reload();
                }else{
                    $('.edit_city_form_alert').html('<div class="alert alert-danger"><i class="fa fa-check"></i> '+data.message+'</div>');
                    setTimeout(function(){$('.edit_city_form_alert').empty();}, 2000);
        }}});
    });    
    del_city_form.on('click', (i) => {
        let cat = {};
        cat.id = i.currentTarget.dataset.id;
        cat.type = i.currentTarget.dataset.type;
        cat.lang_key = i.currentTarget.dataset.lang_key;
        Wo_DeleteCat(cat);
    });

    $('.check-all').on('click', function(event) {
        $('input:checkbox').not(this).prop('checked', this.checked);
    });
    $('.delete-checkbox, .check-all').change(function(event) {
        $('.delete-selected').attr('disabled', false);
        $('.delete-selected').find('span').text(' (' + $('.delete-checkbox:checked').length + ')');
    });

    $('.delete-selected').on('click', function(event) {
        event.preventDefault();
        $('#SelectedDeleteModal').modal('show');
    });
});
</script>