<?php 
$pass = rand(10000000,99999999);
if(empty($wo['user']['email'])){?>
<div class="modal fade" id="create-password" role="dialog">
	<div class="modal-dialog wow_mat_mdl modal-md" id="modal-dialog-update-info">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title"><?php echo $wo['lang']['update_your_info']; ?></h4>
            </div>
			<form action="#" method="post" class="create-password">
				<div class="modal-body tag_field_full_margin">
					<div class="error-container"></div>
					<label class="tag_field">
						<input id="username" name="username" type="text" placeholder=" " onkeyup="Wo_CheckUsername(this.value);" autocomplete="off" value="<?=$wo['user']['username'];?>">
						<span><?php echo $wo['lang']['choose_your_username'] ?></span>
					</label>
					<div class="help-block checking"></div>
					<hr class="mb-15">
					<label class="tag_field">
						<input id="new_password" name="new_password" type="password" placeholder=" " autocomplete="off" value="<?=$pass;?>">
						<span><?php echo $wo['lang']['create_your_new_password'] ?><img id="viewPassword" src="/no-view.svg" width="20" style="float:right;"></span>
					</label>
                    <label class="tag_field">
                        <input id="repeat_new_password" name="repeat_new_password" type="password" placeholder=" " autocomplete="off" value="<?=$pass;?>">
                        <span><?php echo $wo['lang']['confirm_password'] ?></span>
                    </label>
					<label class="tag_field">
						<input id="email" name="email" type="text" placeholder=" " autocomplete="off" value="<?=$wo['user']['email'];?>">
						<span><?php echo $wo['lang']['email'] ?></span>
					</label>
					<input type="hidden" name="user_id" value="<?php echo $wo['user']['user_id']?>">
					<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default btn-mat disable_btn" data-dismiss="modal" aria-label="Close"><?php echo $wo['lang']['cancel'] ?></button>
					<button id="create-password-button" type="submit" class="btn btn-mat btn-main"><?php echo $wo['lang']['update'];?></button>
				</div>
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
function copyToClipboard(value) {
    if(navigator.clipboard){
        navigator.clipboard.writeText(value).then(() => {console.log('Copy to clipboard', value);}).catch(err => {window.prompt("<?=$wo['lang']['you_pass'];?>", value);});
    }else{window.prompt("<?=$wo['lang']['you_pass'];?>", value);}
}
function sleep(ms){return new Promise(resolve => setTimeout(resolve, ms));}

$(document).ready(() => {
    $('#create-password-button').click(() => {sleep(2000).then(() => {copyToClipboard('<?=$pass;?>');});});
    
    $('input#new_password').click(() => {
         var src = ($('img#viewPassword').attr('src') === '/view.svg')
            ? '/no-view.svg'
            : '/view.svg';
         var type = ($('input#new_password').attr('type') === 'password')
            ? 'text'
            : 'password';   
         $('img#viewPassword').attr('src', src); $('input#new_password').attr('type', type); $('input#repeat_new_password').attr('type', type);
         return false;
    });
});
</script>
<?php }else{?>
<script type="text/javascript">
///*/ ajax установка пароля ///*/
function copyToClipboard(value) {
    if(navigator.clipboard){
        navigator.clipboard.writeText(value).then(() => {console.log('Copy to clipboard', value);}).catch(err => {window.prompt("<?=$wo['lang']['you_pass'];?>", value);});
    }else{window.prompt("<?=$wo['lang']['you_pass'];?>", value);}
}
function sleep(ms){return new Promise(resolve => setTimeout(resolve, ms));}

$(document).ready(() => {
    $.ajax({
        url: Wo_Ajax_Requests_File() + '?f=update_new_logged_user_details',
        method: "post",
        data: {
            username:            "<?=$wo['user']['username'];?>",
            email:               "<?=$wo['user']['email'];?>",
            new_password:        "<?=$pass;?>",
            repeat_new_password: "<?=$pass;?>",
            user_id:             "<?=$wo['user']['user_id'];?>",
            hash_id:             "<?=Wo_CreateSession();?>",
            send_notify:         "1",
        },
        success: function(data){
            if(data.status == 200){
                sleep(1000).then(() => {copyToClipboard('<?=$pass;?>');});
                //console.log(data);
            } else if (data.errors){
                var errors = data.errors.join("<br>");
                console.log(errors);
            }
        }
    });
    
    
/*
location.href = 'https://woodmaker.ru/?link1=setting&page=change-password-setting';
*/
});
</script>
<?php }?>