<?php 
    $fid = $wo['field']['fid'];
    if(!empty($cats = Wo_GetCategoriesWithSub())){
        foreach($cats as $k => $cat){
            if('blog' == $cat['type']){
                $cats_blog[] = $cat;
            }elseif('status' == $cat['type']){
                $cats_status[] = $cat;
    }}}
    
    //pa($cats_blog);
    //pa($cats_status);
?>
<div id="dropdown-<?= $fid;?>" class="tag_srch_fltr_country dropdown post_themes_dropdown dropdown_categories">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M3,3H11V7.34L16.66,1.69L22.31,7.34L16.66,13H21V21H13V13H16.66L11,7.34V11H3V3M3,13H11V21H3V13Z" /></svg>
    <div class="d-flex align-items-center category_dropdown_header" data-original-title="<?= $wo['lang']['choose_topic']; ?>" data-toggle="tooltip" data-placement="bottom">                                    
    <span><?= $fid == 'fid_3' ? $wo["lang"]["choose_directions_woodworking"] : $wo["lang"]["woodworking_reason"]; ?></span>
        <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" fill="currentColor" class="bi bi-caret-down-fill" viewBox="0 0 16 16">
            <path d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
        </svg>
    </div>
    <div class="themes_dropdown_body dropdown-menu">
        <p class="dropdown-menu_desc">
            <?= $fid == 'fid_3' ? $wo['lang']['search_categories_prompt'] : $wo['lang']['add_your_status']; ?>
        </p>
        <ul>
            <li class="themes_dropdown_item none_selected"><?php echo $wo["lang"]["none_selected"]; ?></li>
            <?php foreach($fid == 'fid_3' ? $cats_blog : $cats_status as $category_id => $category) { ?>
                <li data-id="<?= $category['lang_key'];?>" class="themes_dropdown_item"><?= $wo['lang'][$category['lang_key']]; ?></li>
            <?php }; ?>
        </ul>
    </div>
</div>

<script>
$(document).on('mouseup', function() {
	$(".category_dropdown_header").each((i, header) => {
		$(header.nextElementSibling).removeClass("show")
	})
})

$("#dropdown-<?php echo $wo['field']['fid'];?> .category_dropdown_header").on("click", function (e) {
    e.stopPropagation()
    if($("#dropdown-<?php echo $wo['field']['fid'];?> .themes_dropdown_body").hasClass("show")) {
        $("#dropdown-<?php echo $wo['field']['fid'];?> .themes_dropdown_body").removeClass("show")
    } else {
        $("#dropdown-<?php echo $wo['field']['fid'];?> .themes_dropdown_body").addClass("show")
    }
})

$("#dropdown-<?php echo $wo['field']['fid'];?> .themes_dropdown_item").each((i, item) => {
    $(item).on("click", function () {
		$('#dropdown-<?=$wo['field']['fid'] ;?> .category_dropdown_header span').text($(item).text())

        $("#dropdown-<?php echo $wo['field']['fid'];?> .post_themes_dropdown span").text($(item).text())

        $("#dropdown-<?php echo $wo['field']['fid'];?> .themes_dropdown_item").each((index, category) => {
            $(category).removeClass('active')
        })
        if(!$(item).hasClass("active")) {
            $(item).addClass("active")
        }
        $("#dropdown-<?php echo $wo['field']['fid'];?> .themes_dropdown_body").removeClass("show")
    })
})
</script>